Dockerfile, docker/Dockerfile, docker/README.md
Currently, this Dockerfile:
- Mounts the repo we run build from to boot-clj
- Pulls all deps that clj-docs needs to run analysis
Tested against a couple of jars to ensure docs generate properly.
As far as getting documents out of the container we can either mount a volume or call `docker cp` to copy them out.
=> Add initial Dockerfile.

docker/README.md
The current suggested commands for running the container leave stopped containers, which can be solved by adding the `--rm` flag when we run the containers.
=> Add --rm switch to remove stopped containers

build.boot, src/cljdoc/git_repo.clj
This is based on the implementation in gitlibs, and should function very
similarly.
Documentation:
> ssh authentication works by connecting to the local ssh agent (ssh-agent on
> *nix or Pageant via PuTTY on Windows). The ssh-agent must have a registered
> identity for the key being used to access the Git repository. To check whether
> you have registered identities, use:
> ssh-add -l
> which should return one or more registered identities, typically the one at ~/.ssh/id_rsa.
----
I've perhaps not tested this as thoroughly as it requires.
=> Add SSH agent authentication support

src/cljdoc/renderers/html.clj
Much easier to navigate, can find docs with `CTRL+F` etc.
=> always show expanded doc-tree

src/cljdoc/renderers/html.clj
Hey @martinklepsch!
Took a quick stab at the source links issue. LMK what you think.
=> Use the commit SHA if the release isn't tagged. Fixes #43.

build.boot, src/cljdoc/render/api.clj
As written, this uses a hard-coded 70 column width, since that seems to be about the available space.  The default of 80 was definitely too big, things were still cut off.  If there is some configuration for width of the html output, I'd be happy to integrate with that.  I tested this on generating API documentation for zprint itself (which has some pretty big arglists) and they came out fine.
Oh, one small thing.  The latest repo I cloned failed when I ran it because there was no `data` directory, but once I created it by hand, it worked fine.  That seems to be a new thing, as the previous version I tried this on didn't have that problem.  No big deal, the error is quite clear.
=> Use zprint to format arglists to fit within available space.

.gitignore, build.boot, src/cljdoc/render/build_req.clj, src/cljdoc/server/api.clj, src/cljdoc/server/release_monitor.clj, src/cljdoc/util.clj, src/cljdoc/util/clojars.clj, src/cljdoc/util/repositories.clj, test/cljdoc/util_test.clj
Clojure is not hosted on Clojars.
Including Maven Central in the repositories list allows Clojure to be
documented. Note that clojure.parallel fails, but the docs are still
generated for other namespaces. clojure.parallel is deprecated.
=> @alex-dixon/@timothypratley: adds maven central as a repository

.circleci/config.yml, build.boot, ops/create-secrets.cljs, ops/run-cljdoc-api.sh, resources/config.edn, resources/config.min.edn, resources/config.template.edn, resources/secrets.edn, src/cljdoc/config.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/util/sentry.clj
Fixes #48
This adds error tracking via [Sentry](https://sentry.io/). Disabled in non-prod profile.
=> track errors in production

build.boot, resources/public/cljdoc.css, src/cljdoc/cache.clj, src/cljdoc/render/api.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/offline.clj, src/cljdoc/renderers/html.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/util.clj, src/cljdoc/util/fixref.clj, test/cljdoc/util_test.clj
Sometimes it's very convenient to allow users to view documentation offline, e.g. when on flights or simply for tools like [Dash](http://kapeli.com/dash) or [Zeal](https://zealdocs.org/).
This PR introduces another endpoint:
```
/download/reagent/reagent/0.8.1
```
That will download a zipfile `reagent-0.8.1.zip`. This zip file contains all documentation in a slightly more lean layout and with an overview `index.html` that lists all interesting things.
Until this is deployed you can see some examples here. I would be very happy about any feedback with regards to the bundled docs & the code introducing this change:
- [manifold-0.1.6.zip](https://github.com/martinklepsch/cljdoc/files/2144612/manifold-0.1.6.zip)
- [reagent-0.8.1.zip](https://github.com/martinklepsch/cljdoc/files/2144613/reagen …
=> Offline docs

src/cljdoc/doc_tree.clj
#87 Small tweaks to doc-tree to add changelog detection and inclusion in the table of contents.
=> Add changelog as article when present

resources/public/cljdoc.css, resources/public/cljdoc.js, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj
closes #20 
Not really sure if it's what you had in mind but I took a swing at it anyways.
Some open topics are what level of header it should display (like should h4's and above not get added) and whether the top margin on body should be reduced.
It's the bar with the current section for anyone that doesn't want to build it:
=> added section headers to doc pages for easier nav

resources/public/cljdoc.css, resources/public/cljdoc.js, src/cljdoc/render/api.clj
Sometimes the renderer mangles some quasi md in docstrings. I started to think about extending the md parser but i think it's an intractable problem. so instead add a option to just render the raw docstring. Motivating example in the images from `re-frame.std-interceptors`'s docstring:
=> added toggle raw

src/cljdoc/render/api.clj
fixes #119 
**issue to be solved:** 
at the moment, the toggle `raw docstring` is always shown, even when no docstring is available
**solution:**
only show the toggle when `render-doc` returns something else than `nil`
ideas or suggestions for improvements are welcome 😃
=> Show toggle for `raw docstring` when docstring exists

resources/public/switcher.js
Change switcher shortcut from `k` to `cmd` + `k` on Mac and `ctrl` + `k` on windows.
Use keydown events to correctly handle key combinations.
=> Change switcher shortcut k -> 'cmd/ctrl + k'

modules/shared-utils/src/cljdoc/util.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/offline.clj, src/cljdoc/util/fixref.clj, test/cljdoc/util_test.clj
Support Gitlab URLs in repo link & icon and update "Edit on Github" link at bottom of article.
=> Support Gitlab URLs

doc/running-cljdoc-locally.md
1. Pin down the version of muuntaja to 0.6.1
1. Use `scripts/lein-modules install` to build muuntaja because
the project has splitted into different modules. This will make
sure the dependencies to individual modules are resolved properly.
=> Update Running cljdoc locally documentation

src/cljdoc/cli.clj, src/cljdoc/config.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/release_monitor.clj, src/cljdoc/server/system.clj
SQLite has been used for a while before eventually all data has been migrated into it (see [ADR#0013](https://github.com/cljdoc/cljdoc/blob/master/doc/adr/0013-move-to-sqlite-for-storage.md)). This resulted in some drift between the database file name and what it was actually used for. Previously only used for build logs the file name was `build-log.db` but after the migration this is no longer accurate.
This PR changes the filename and related functions while still supporting the old location (with a warning being logged).
=> Fix db name

resources/migrations/005-add-analyzer-version-column-to-builds.down.sql, resources/migrations/005-add-analyzer-version-column-to-builds.up.sql, script/trigger-circle-analysis.sh, src/cljdoc/analysis/service.clj, src/cljdoc/config.clj, src/cljdoc/server/api.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/system.clj
Fixes #151. This allows us to link builds to analyzer versions making it easier to detect regressions with newer releases.
=> fix #151: make analyzer version a circle ci build parameter

.circleci/config.yml
This prevents deploys from running in pull requests (which fail because env vars aren't exported) and on cljdoc branches (which would presumably succeed).
=> Only run the deploy on master branch

src/cljdoc/render/error.clj, src/cljdoc/server/pedestal.clj
This PR addresses issue #32.
1. Add custom interceptor for handling 404 error
1. Add ns, `cljdoc.render.error`, for rendering the error page
Here's a snapshot of the 404 page:
On smaller mobile device (iPhone 6)
On larger mobile device (iPhone 6 plus)
Any feedback is welcome :) Thanks!
=> Add better 404 page

modules/analysis-runner/src/cljdoc/analysis/runner.clj, modules/shared-utils/src/cljdoc/util/deps.clj
also print analyzer result before reading the cljdoc edn, because this fails when the analyzer failed.
Fixes #147
=> only include deps of scope 'provided`, 'system' and 'test'

modules/shared-utils/src/cljdoc/spec.cljc, src/cljdoc/bundle.clj, src/cljdoc/render/api.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/renderers/html.clj, src/cljdoc/storage/sqlite_impl.clj
While the proper way would have been to check the latest release with `repo.clojars.org`
I decided to just check what's in the database. This avoids the network roundtrip and
through the automatic building of releases things should be somewhat in sync anyways.
This also has the added benefit of only showing the notice when docs have been successfully
built saving the user from clicking and then being asked to run the build (which may fail).
Fixes #161
=> Inform users if a newer release is available

src/cljdoc/render/layout.clj, src/cljdoc/renderers/html.clj
Deliberately delaying this until .org migration (#158) is done.
=> Add <link rel="canonical"> to point to recent version

src/cljdoc/render/build_req.clj
This makes it clearer which parts cljdoc is using for searching and can help show people why they might have gone wrong. Adding the "v" in front of the version by itself looks slightly confusing. It's not obvious that it was added in the formatting, but wasn't included in the search.
=> Bold artifact coordinates for request-build-page

src/cljdoc/render/home.clj
This will stop it from being out of date as new releases are made.
We could also do a DB query here, but it's probably ideal to not need a DB query to load the homepage.
=> Use the CURRENT url path for homepage projects

src/cljdoc/render/error.clj, src/cljdoc/render/home.clj
Improves the mobile styling for #156 in a small way.
Before/after
Before | After
:------:|:--------:
=> Remove margin from homepage and 404 page on mobile

deps.edn, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/server/sitemap.clj, src/cljdoc/storage/api.clj, src/cljdoc/storage/sqlite_impl.clj
Fixes #162 
Here's a summary of what this PR does:
- Add `sitemap` as a dependency
- Add a /sitemap.xml route
- Create ns cljdoc.server.sitemap
- Add a storage API `all-distinct-docs` which queries the versions table for distinct (group_id, artifact_id) pairs
- Resolve urls based on (group_id, artifact_id) pairs and transform them to sitemap.xml
Things yet to be done:
Below is what I got so far. Please feel free to give me your comments. Thanks!
=> Create a sitemap

src/cljdoc/analysis/service.clj, src/cljdoc/cli.clj, src/cljdoc/render/build_log.clj, src/cljdoc/server/api.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/server/system.clj, test/cljdoc/integration_test.clj
The process of building documentation can be thought of as two steps:
1. Analysing a Jar and extracting information about a projects API
2. Analysing a projects Git repository to include a README, provide correct source links etc.
So far the order above has also been the order in which those steps were executed but it turns out that under some circumstances the information from the Git repository may be relevant for the Jar analysis. Primarily users may want to further configure the Jar analysis via the `cljdoc.edn` file in their Git repository (see #107 for more details).
This PR. changes the order of the two steps above, only triggering the CircleCI job after the Git analysis has been completed (successfully or not).
=> Reverse order of analysis

js/cljdoc.js, js/doctree.js, js/index.js, js/mobile.js, src/cljdoc/render/api.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/renderers/html.clj
Fixes #156 
👉 See a [video preview](https://giant.gfycat.com/EthicalGraveFairyfly.mp4). 
This makes all the main documentation pages of cljdoc responsive and introduces a special UI element that helps to switch between navigation and documentation content. The UX is largely inspired by Docusaurus ([example page](https://docusaurus.io/docs/en/adding-blog)).
This also replaces a bunch of nested `absolute` and `fixed` elements and makes heavy use of Flexbox, making the entire layout a bit easier to work with (or wieldy as some like to say).
I'd appreciate if other contributors could give this a go locally and report back any issues.
--- 
Interestingly what was hardest about this is getting the scroll behaviour right. Smooth momentum based scrolling as well as automatic collapsing of the URL …
=> Responsive Documentation Pages

.circleci/config.yml, .circleci/run_if_changed.sh, modules/analysis-runner/deps.edn, modules/analysis-runner/extended-test.clj, modules/analysis-runner/src/cljdoc/analysis/deps.clj, modules/analysis-runner/src/cljdoc/analysis/runner.clj, modules/shared-utils/src/cljdoc/util.clj, modules/shared-utils/src/cljdoc/util/pom.clj, src/cljdoc/analysis/service.clj, src/cljdoc/cli.clj
This improves the situation around the analysis runner in a few ways:
- It's more decoupled from the rest of the server code. Previously the local analysis service would call `analyze-impl`. Now it shells out which will launch another `clojure` process. This is only for development but allows a cleaner separation of dependencies etc.
- A testing script that runs the analysis runner in various project and reports the results in a nice table. Thanks `clojure.pprint`!
- Some more scripts to run that testing script whenever the analysis runner changed.
- More docstrings in the analysis-runner related namespaces
- The classpath is now computed within the analysis runner and passed to `clojure` via `-Scp`. This should make things faster and allow us to further customise the resolved deps should …
=> Various analysis runner improvements

src/cljdoc/storage/sqlite_impl.clj
excluding snapshot versions from the "new version available" warning
=> Fix for #203

js/index.js, js/search.js, resources/public/opensearch.xml, src/cljdoc/render/error.clj, src/cljdoc/render/home.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/search.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj
References the issue #186 
This PR is not ready to be merged yet. Please provide feedback on the code change.
The search page still need a link for the user to go back to the home page.
=> Open search config + search page

doc/adr/0016-prefer-polling-over-webhooks.md, modules/shared-utils/src/cljdoc/util.clj, src/cljdoc/analysis/service.clj, src/cljdoc/cli.clj, src/cljdoc/server/api.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/ingest.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/server/system.clj
See [ADR 0016](https://github.com/cljdoc/cljdoc/blob/bd8eb200eb6fe0ac8f3425a28b354d196cab32af/doc/adr/0016-prefer-polling-over-webhooks.md) for a rationale behind this change.
There's probably still some more cleanup to do before merging this.
=> Poll CircleCI instead of relying on webhooks

src/cljdoc/render/api.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj
- Remove the indentation of article and namespace trees relative to their sidebar titles
- Introduce some better visual separation between sidebar sections
- Minor code improvements to the way `main-list` and `article-list` work
@dawran6 The destination of this PR is your branch (#227) so you can just merge it if you like it 🙂
=> Minor fixes for PR #227

src/cljdoc/render/api.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/sidebar.clj, src/cljdoc/renderers/html.clj
There now is one function to render the sidebar. This function receives the same arguments as the other main rendering entry points: `route-params` and `cache-bundle`.
The small notes indicating a problem have been updated to more accurately report what is going on, specifically the following scenarios are handled:
- No articles were found at all.  
**Causes**: No Git repo found or unsupported document types. 
**Solution**: Point user towards relevant documentation.
- Only Readme and Changelog were found.  
**Causes**: Articles haven’t been set up.  
**Solution**: Point user to articles documentation
- No namespaces were found. 
**Causes**: Failed analysis or Uber-module artifact without actual sources. 
**Solution**: Invite users to open an issue.
The separators have also been changed …
=> Refactor sidebar rendering

src/cljdoc/util/repositories.clj
Update `get-pom-xml` function to check if POM file exists locally.
Fetch it locally if exists otherwise check on Maven Central.
fixes #258
=> Get POM XML from local repo

.circleci/config.yml, doc/custom-articles.adoc, resources/public/cljdoc.css, src/cljdoc/config.clj, src/cljdoc/doc_tree.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/rich_text.clj, src/cljdoc/renderers/html.clj, src/cljdoc/server/system.clj, test/cljdoc/doc_tree_test.clj
This PR opens up article types to be extended beyond Markdown and Asciidoc. This will be useful for experimental extensions like Cucumber feature files as described in #257 as well as proprietary formats used inside organisations with an on-premise cljdoc deployment. 
One aspect I'd particularly appreciate feedback about is the whole `filepath->type` stuff. Basing this purely on the extension seems a little too constrained and the most appropriate approach would probably be a sequence of predicates. That's not as nice as multi methods however and would require some manual state-wrangling in the form of an atom or similar. Wouldn't be the end of the world, multimethods are just state anyways but still, multimethods are more familiar and very well integrated into the language.
=> Extensible article types

js/index.js, js/navigator.js, src/cljdoc/render/index_pages.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj
This PR adds two things (in one commit, sorry about that):
1. A global index page under `/versions`
- **Rationale:** cljdoc is now used internally at a company (cool! 🎉) and discoverability of documentation has been an issue. By having a global index this should be a solved problem. The global index is probably less useful in the live cljdoc instance (due to sheer amount of libs) but the code has been fairly minimal so I think it's ok to have it.
1. A small JS component that allows you to enter a project and a version and jump to the documentation for the specified project
- **Rationale:** cljdoc's search is pretty buggy and Clojars specific at this point and memorising the URL pattern `/d/$group-id/$artifact-id/$version` imposes additional mental load on people trying to find docs. This …
=> Global Index Page + Navigator JS Component

deps.edn, doc/userguide/for-library-authors.adoc, modules/shared-utils/src/cljdoc/util.clj, modules/shared-utils/src/cljdoc/util/pom.clj, resources/sql/sqlite_impl.sql, src/cljdoc/analysis/git.clj, src/cljdoc/bundle.clj, src/cljdoc/render/api.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/offline.clj, src/cljdoc/render/sidebar.clj, src/cljdoc/renderers/html.clj, src/cljdoc/server/ingest.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/system.clj, src/cljdoc/storage/api.clj, src/cljdoc/storage/sqlite_impl.clj, src/cljdoc/user_config.clj, src/cljdoc/util/fixref.clj, test/cljdoc/analysis/git_test.clj, test/cljdoc/integration_test.clj, tests.edn
Fixes #24 
Fixes #198 
This PR significantly improves cljdoc's usability with regards to libraries consisting of multiple modules/separate jars. Notably the following features are added:
If a repository contains the code for multiple artifacts it might be desirable to provide different doc trees for those artifacts. This can be used to point users to the "ubermodule" documentation or to provide more detailed documentation on a module.
Ubermodule libraries often don't contain any actual code and rely on dependencies to import functionality. Users can now provide a `:cljdoc/include-namespaces-from-dependencies` key to include APIs from dependencies in the documentation of an artifact.
💡  For details on how to use those features, check the [changes to the user …
=> Improved support for modular libraries

resources/public/cljdoc.css
Since this is a quick change, I'm creating a PR instead of asking first. It is subjective, but using a single monospace font everywhere looks nicer to my eyes. We should probably update the screenshot on home page, maybe I missed some other monospace usage as well.
Feel free to close this, if it doesn't fit into your vision of cljdoc design.
=> Use single monospace font style everywhere

modules/analysis-runner/extended-test.clj, modules/analysis-runner/src/cljdoc/analysis/deps.clj, modules/analysis-runner/src/cljdoc/analysis/runner.clj, modules/analysis-runner/src/cljdoc/analysis/runner_ng.clj, modules/cli/src/cljdoc/cli.clj, modules/shared-utils/src/cljdoc/util.clj, src/cljdoc/server/ingest.clj
* use it for building CP (#273)
* use artifact version from analysis result instead of pom's one
=> Improvements for ingesting local JARs

src/cljdoc/render/api.clj, src/cljdoc/render/layout.clj
Moved docstring platform indication into the (widened) left margin.
Before:
After:
=> UX(docstrings): show docstring platform in margin. Closes #280.

src/cljdoc/render/api.clj
I came across this broken page:
https://cljdoc.org/d/buddy/buddy-core/1.5.0/api/buddy.core.mac
After being able to reproduce the same issue locally, I discovered what was causing the error:
The function [here](https://github.com/funcool/buddy-core/blob/master/src/buddy/core/mac.clj#L70) has a strange definition with a doc string which is then overwritten with `{:doc false}`.
I think cljdoc should handle `{:doc false}` in general.
Not sure what is the best way to handle it but with the fix, the page renders and the missing doc string looks like this:
And raw mode:
=> Handle {:doc false} when rendering doc string

resources/migrations/007-builds-index.down.sql, resources/migrations/007-builds-index.up.sql, src/cljdoc/render.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/sidebar.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/pedestal.clj
The badges are a useful way to provide information about the state of a project to it's authors and other users. To make it even more useful it should display information about the build status if there has been a problem.
Fixes #243
=> Integrate build status into badge + docs pages

doc/running-cljdoc-locally.md, ops/docker/Dockerfile, ops/docker/Makefile
@martinklepsch Please test the updated instructions before merging :-)
One thing to keep in mind: the docs assume that there is a `latest` tag on Dockerhub which points to the latest image (this is common). I've updated the `Makefile` to create the `latest` tag and I'm assuming that the `.circleci/config.yml` will push that tag to Dockerhub.
=> Documentation about running locally with Docker

resources/migrations/007-create-stats-table.down.sql, resources/migrations/007-create-stats-table.up.sql, src/cljdoc/server/clojars_stats.clj, src/cljdoc/server/system.clj
This is mostly taken from https://github.com/cljdoc/clojars-stats. Eventually this data will be incorporated into search results and the overall UI of cljdoc.
All access to the stats data is intended to go through `IClojarsStats`, currently with only one function `artifact-monthly`.
For some reason SQLite doesn't properly recognise the uniqueness index when running queries. To fix this we need to run `analyse clojars_stats;` after deploying this change.
=> add clojars-stats component that caches stats in SQLite

src/cljdoc/server/search/artifact_indexer.clj, src/cljdoc/server/search/search.clj
E.g. clojure at Clojars is old, 1.5 version. We only want the latest
and thus from Maven Central.
=> Search: Ignore Clojure Contrib libs from Clojars

src/cljdoc/server/search/search.clj
e.g. "metosin muuntaja". The multi-tokens->query
required that all tokens are present (MUST) but the problem is
that it is run for each field while the tokens might be in different
fields.
We still need to do something so that hits with _all_ the tokens
(possibly across multiple fields) are the top.
=> Search: fix no match for "<group> <artifact>"

modules/analysis-runner/src/cljdoc/analysis/deps.clj
Setting up proper tests for this would be great but for now I just wanted to get it fixed.
```
(-> (resolved-and-cp
"/Users/martinklepsch/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.jar",
"/Users/martinklepsch/.m2/repository/cljdoc-298/cljdoc-298/1.0.0/cljdoc-298-1.0.0.pom"
{})
:resolved-deps
(get 'org.clojure/clojurescript)
:mvn/version
(= "1.10.520"))
```
Thanks to @mfikes for his excellent repro in #298.
=> Fix issues with wrong Clojure and ClojureScript versions

src/cljdoc/server/search/artifact_indexer.clj
Following discussion on this issue: https://github.com/cljdoc/cljdoc/issues/308#issuecomment-530584697
Notes:
- I did not include the quotes in the search as they do not seem useful
```
http://search.maven.org/solrsearch/select?q=g:%22org.clojure%22+OR+g:%22com.turtlequeue%22&rows=200
```
returns the same as
```
http://search.maven.org/solrsearch/select?q=g:org.clojure+OR+g:com.turtlequeue&rows=200
```
- the `description` will be wrong https://github.com/cljdoc/cljdoc/blob/1eaaac904b275ebe581f1775a3c4b5bb44e43bdd/src/cljdoc/server/search/artifact_indexer.clj#L36
=> Add com.turtlequeue to group IDs searched on Maven Central

src/cljdoc/render/index_pages.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/pedestal_util.clj, src/cljdoc/server/search/artifact_indexer.clj, src/cljdoc/server/system.clj, test/cljdoc/integration_test.clj
so that Dash can use it to fetch the available versions of a document.
(Impl.: Transform versions seq into the versions-tree of
group->artifacts->versions, all sorted, use it everywhere.)
Fixes #350
=> Support also JSON, EDN for /versions/*

src/cljdoc/server/pedestal.clj, src/cljdoc/server/pedestal_util.clj
Looking at that code to understand the search issue I had a bit of a hard time understanding what the `transformer` is actually doing. It is passed down very far and in many places augmented/changed slightly making overall program flow a little hard to understand (to me). 
I'm pretty sure there are still issues with this PR, particularly the `show-build` interceptor may need some touching up, but I wanted to open this just to get your thoughts on the general refactoring @holyjak.
=> Refactor how HTML body is created in coerce-body helpers

.gitignore, src/cljdoc/server/routes.clj, test/cljdoc/server/routes_test.clj
This shall fix #348 .
In https://github.com/cljdoc/cljdoc/issues/348#issuecomment-531135828 it's suggested to fix it by use two separate routes:
```clojure
["/badge/project-id" :get nop :route-name :badge-for-project]
["/badge/group-id/artifact-id" :get nop :route-name :badge-for-project]
```
However I think using constraints are slightly better because pedestal requires each route to have a unique name, which means we need to duplicate the `:badge-for-project` entry in the `route-resolver` function:
https://github.com/cljdoc/cljdoc/blob/f08a21696d887c0c357a3f75338167c1d5b18d6b/src/cljdoc/server/pedestal.clj#L431-L433
(It's a pity that pedestal doesn't support capturing path params with regular expressions, btw)
=> Fix badge routes

src/cljdoc/render.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/search/api.clj, src/cljdoc/server/search/artifact_indexer.clj, src/cljdoc/server/search/search.clj
Build on #357 to return all versions.
Also improves indexing to get all versions of Maven Central artifacts and to fetch descriptions for those that have one.
=> Fix #350 /versions API include unbuilt

resources/config.edn, test/cljdoc/util_test.clj
More info: https://support.sonatype.com/hc/en-us/articles/360041287334
See https://github.com/cljdoc/cljdoc/issues/376
=> Builds using maven central are failing because http vs https.

doc/running-cljdoc-locally.md
Add a section 'Dependencies cljdoc' in the documentation page 'running-cljdoc-locally.md'.
Fixes #381
=> Update running cljdoc locally page: dependencies

doc/running-cljdoc-locally.md
This is necessary because the URL without 0.6.1 defaults (upon pressing enter)
to 0.6.6 which is just not the version installed locally when following
the instructions.
=> add version 0.6.1 to muuntaja URL in running-cljsdoc-locally.md

src/cljdoc/bundle.clj, src/cljdoc/render/api.clj
fixes #21, ready to merge into master
bundle.clj: in function has-defs, add or condition for :doc key
render/api.clj: format the two "No vars..." messages uniformly in italic blue
=> If namespaces has doctring but no vars, display it as well in sidebar

src/cljdoc/server/api.clj
Fixes #363, ready to merge into master.
During the build process as implemented pre-this-PR:
When the SCM-URL does for some reason not make it into the function "kick-off-build" (i.e. is nil), the message "in progress" is displayed and never changes. The already implemented print of a nice explanation message is never triggered.
With this PR, the nice message is now actually shown on screen, with the new additional message "Error while trying to process Git repository: no SCM URL found" included.
=> Improve Git analysis error reporting

src/cljdoc/server/api.clj
Turns out this actually isn't appropriate to do since some libraries don't contain namespaces and that's fine. The red message highlighting this in the build page is sufficient to make people aware. 
Reverts cljdoc/cljdoc#389
=> Revert "Throw exception when no namespace is found"

js/cljdoc.js, js/index.js, src/cljdoc/render/articles.clj
Hello, this is a super naive implementation to fix #28 
- add `id` attribute to links for next and prev page
- add a function that listens to keyboard events and navigate to the page from that link
=> add keyboad navigation

.clj-kondo/config.edn, deps.edn
Clj-kondo now includes a user config by default.
This is now disabled for cljdoc.
=> Update to current clj-kondo

src/cljdoc/render.clj, src/cljdoc/render/articles.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/offline.clj, src/cljdoc/util/datetime.clj, src/cljdoc/util/fixref.clj, src/cljdoc/util/scm.clj, test/cljdoc/util/fixref_test.clj, test/cljdoc/util/scm_test.clj
Fixes #421.
* [microicon](https://microicon-clone.vercel.app/) does not have a sourcehut icon, but I suppose the generic git icon is good  enough.
* Published [org.clojars.miikka/sourcehut-and-cljdoc 0.1.0-SNAPSHOT](https://clojars.org/org.clojars.miikka/sourcehut-and-cljdoc) which has a README with an image and relative links, so it's easy to test that this patch works.
To-do:
=> Add support for Sourcehut as a SCM provider

js/switcher.js
On Firefox and Chrome (the ones I tested), when you press `Ctrl+K`
the browser's navigation bar gets focused and adds a question mark
for searching, which prevents the user from using this as an actual
feature. Calling `preventDefault` on the event, makes the cljdoc
search box to get focused instead.
**Reference**:
* Chrome: https://support.google.com/chrome/answer/157179
* Firefox: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search
**Note**: I don't know if this could be the better option, if you're trying not to obstruct the user's usual interaction with the browser. But, at least, letting it here as a note.
=> Prevent default behavior for Ctrl-K

src/cljdoc/render/rich_text.clj
When cljdoc encounters a relative path, it will look for it in the list
of _source files_.  This is because it's operating similarly to GitHub
where the link ends in `.md`, rather than `.html` as the output format.
Cross references use outfilesuffix to automatically add a suffix as is
appropriate for their platform, by default when generating html output
that suffix is `.html`.  To allow cljdoc's URL fixer to run, we instead
make this output `.adoc`, which allows the path to be found in the list
of source files again.
=> Fix adoc xrefs

deps.edn
Newer versions of Clojure cli warn on unqualified deps in deps.edn,
qualify them to rid ourselves of the warnings.
Contributes to #413
=> Qualify dependencies in deps.edn

.clj-kondo/config.edn, .cljfmt/indentation.edn, deps.edn, test/cljdoc/doc_tree_test.clj
This should help to rid us of a sporadic test failure - and if a failure recurs we'll now be able to reproduce it.
=> Find neighbour article tests now use test.check

bb.edn
The most recently released version clojure-lsp has an issue with paths
being symbols even though babashka allows them. See link.
https://github.com/clojure-lsp/clojure-lsp/issues/507
=> Fix bb.edn so clojure-lsp doesn't crash.

deps.edn, src/cljdoc/server/search/artifact_indexer.clj
The artifact indexer was failing for me every time it ran. The maven
servers kept giving us back 429 responses which mean we should back
off on our request rate a little.
So for the implementation I went to add retries with backoff and
discovered that we're using with-open with io/reader on a url to pull
docs from maven. This is less than ideal and we have clj-http-lite
already in the project so it makes sense to switch to that.
This change moves to clj-http-lite and adds robert-bruce for retrying
with backoff on exceptions when requests fail. Now download and
indexing doesn't fall over!
=> Retry maven fetches with clj-http-lite.

src/cljdoc/server/search/artifact_indexer.clj
When I use `./script/cljdoc run` the initial indexing run fails.
Bumping the retries up to 5 makes it work but really we don't want
this to fail in other odd situations and so I'm bumping it way up to 10
tries.
=> Bump retries of maven requests up to 10.

doc/userguide/faq.md, doc/userguide/for-library-authors.adoc
This came up [in Slack](https://clojurians.slack.com/archives/C8V0BQ0M6/p1630341077012500) as potentially confusing. `CURRENT` isn't actually needed unless you want to link to a specific document/namespace and so we can just remove it. Same goes for the old `/jump` routes which I think don't solve any real purpose over the redirects we do with just `/d/project-id` or `/d/group-id/artifact-id`.
=> remove uneccessary CURRENT and old /jump docs

js/cljdoc.ts, js/index.tsx, src/cljdoc/render/offline.clj
There were 2 causes why it was not working:
- cljdocs's `assets/js/index.js` was not included in offline bundles
- raw toggles are not initialized since the `.ns-page` css class was missing in offline bundles
Solution:
- `assets/js/index.js` is included in the offline bundle (using the same as approach as `assets/cljdoc.css` which is already included)
- Adding `.ns-page` did not work. If it is set the Scroll Indicators are initialized as well which are not available in the offline bundle. Therefore a new class `.ns-offline-page` was added which initializes the raw toggle but not the scroll indicators.
=> Fix raw docstring toggle in offline bundles #412

src/cljdoc/render/meta.clj
Hi, this PR is supposed to resolve https://github.com/cljdoc/cljdoc/issues/419
The PR https://github.com/cljdoc/cljdoc/pull/414 already introduced two new keyboard shortcuts:
1) Arrow Left - Navigate to previous page
2) Arrow Right - Navigate to next page
Both shortcuts are now included in the "Keyboard shortcuts" help section.
I changed the view to a Tachyons table layout for this.
=> Add keyboard shortcuts for prev/next page navigation to help (#419)

src/cljdoc/render/meta.clj
Tables were a great addition but we can tighten up the styles a bunch.
Before:
After:
=> Improve shortcut table styles

src/cljdoc/analysis/git.clj
This PR attempts to fix a bug in the git analysis step that causes broken image links in SNAPSHOT releases.
I added a detailed bug description as comment on the ticket: https://github.com/cljdoc/cljdoc/issues/426#issuecomment-933734109
=> Fix broken image links in SNAPSHOT releases (#426)

js/index.tsx, js/recent-doc-links.tsx, js/search.tsx, js/switcher.tsx, package-lock.json, package.json, src/cljdoc/render/home.clj, src/cljdoc/render/search.clj
There's already an abandoned PR for this issue #399 so I thought I'd give it another try. I kept only the first commit of the old PR since merging the complete old PR  would be more effort.
After the page is loaded existing example links are replaced with the most recently visited doc links. If one of the initial example links is used it get's ignored.
Fixes #282
=> Add previously visited doc links on homepage

src/cljdoc/render/home.clj
I believe most people have little use for downloading .zip of docs but there is a fair number of users of Dash and Zeal so it is valuable to mention them right on the home page as they might not guess that offline docs are about more than just the zip download.
=> home: mention dash, zeal right here

ops/docker/Makefile
My change to always rebuild does not jive with
our CircleCI workflow.
The build job packages up cljdoc for the
publish-docker job.
My change to force a full clean does not work
for this strategy. The publish-docker job
does not expect to package up cljdoc.
=> Make docker Makefile a bit less dev-friendly

deps.edn, src/cljdoc/util/fixref.clj, test/cljdoc/util/fixref_test.clj
JSoup HTML pretty printing behavior has changed which caused our url
fixup tests to fail.
We don't need JSoup to pretty-print HTML.
So we've turn this feature off.
This makes current tests clearer as input now matches output
wrt to whitespace/newlines.
=> Upgrade to jsoup v1.14.3

.clj-kondo/config.edn, .gitignore, deps.edn, modules/deploy/src/cljdoc/deploy.clj, modules/shared-utils/src/cljdoc/spec.cljc, src/cljdoc/analysis/service.clj, src/cljdoc/git_repo.clj, src/cljdoc/platforms.clj, src/cljdoc/server/build_log.clj, src/cljdoc/util/fixref.clj, src/cljdoc/util/sqlite_cache.clj
As part of a maintenance sweep have updated
libs we use for linting and testing.
Clj-kondo found a few small things, and had issue
with the singly-namespaced digest library.
The digest library is now hosted under clj-commons,
so updated it to current.
Cljfmt has some slightly new behavior around
whitespace around comments, so adjusted code
formatting to appease it.
Also: now git ignoring /.lsp for those who are using
and loving clojure-lsp.
=> Update dev deps and digest lib

.circleci/config.yml, deps.edn, ops/README.adoc, ops/nvd-check.sh, ops/nvd-config.json, ops/nvd-suppressions.xml, src/cljdoc/git_repo.clj
Of note:
- Jgit
- now includes a specific jsch artifact which has appropriate and
current jsch dependencies.
- included a class reorg which we had to adapt to
- now requires >= JDK11
=> Update more critical Clojure deps

deps.edn
We have quite a few dependencies in cljdoc.
This can be overwhelming.
I've made an attempt to describe and categorize deps in our main deps.edn.
No changes have been made to actual deps in this commit.
=> maint: describe and categorize Clojure deps

deps.edn, src/cljdoc/render/rich_text.clj, src/cljdoc/render/sanitize.clj, test/cljdoc/render/rich_text_test.clj, test/cljdoc/render/sanitize_test.clj
Documentation of libraries that cljdoc imports include markdown in the
form of:
- AsciiDoc and CommonMark articles
- CommonMark in docstrings
We now sanitize this markdown after it is converted to HTML to:
1. primarily protect cljdoc users from potentially malicious HTML
2. secondarily ensure separation of user markdown styling from cljdoc
styling
Testing has been done, but if we learn that we are over-sanitizing,
this is easy enough to correct.
See cljdoc.render.sanitize namespace for more verbiage.
=> Sanitize HTML converted from library markdown

src/cljdoc/analysis/service.clj
This gets cider/orchard past the reported problem, but there is another
issue in the library itself:
https://github.com/clojure-emacs/orchard/issues/150#issuecomment-1020242754
Closes #487
=> Bump cljdoc-analyzer

src/cljdoc/server/pedestal.clj
If a user clicks on x and then y before x is fully delivered,
pedestal logs an extremely verbose broken pipe error.
We work around this with a strategy tonsky blogged about here:
https://tonsky.me/blog/pedestal/#running-the-app
We now simple log an info level "broken pipe" message when
this normal event occurs.
We can do something more proper after this pedestal issue is
addressed: https://github.com/pedestal/pedestal/issues/623
Closes #367
=> Quiet pedestal broken pipe errors

deps.edn, src/cljdoc/render/rich_text.clj
Of note:
- flexmark-ext-gfm-tables has been generalized into flex-mark-ext-tables
- added configuration to make this behave like github tables
- some classes moved around
- added some type hints here and there
=> maint: upgrade flexmark

.clj-kondo/config.edn, deps.edn, src/cljdoc/server/pedestal.clj
Enabled new redundant-fn-wrapper linter.
Much to my surprise, given the number of folks who have worked on
cljdoc, it only found one instance of unnecessary wrapping!
=> maint: upgrade clj-kondo

src/cljdoc/render/rich_text.clj
To preserve GitHub md table rendering after flexmark upgrade,
options need to go on the parser; they were accidentally placed
on the renderer.
=> maint: flexmark upgrade addendum

doc/running-cljdoc-locally.adoc
The cljdoc-exerciser project, which is used as an example, is now
released under org.cljdoc.
=> doc: update running locally

ops/docker/Dockerfile, script/docker-entrypoint.sh, script/get_cljdoc_data_dir.clj
Ask the JVM to dump the heap when it encounters an out
of memory error.
Apparently there is no penalty for this action.
Should be useful in diagnosing our next out of memory error.
Can analyze dump file with tools like:
- jvisualvm
- Eclipse Memory Analyzer
Closes #524
=> ops: have jvm dump heap out of memory errors

doc/running-cljdoc-locally.adoc, src/cljdoc/render.clj, src/cljdoc/render/api.clj, src/cljdoc/render/offline.clj, src/cljdoc/render/rich_text.clj, test/cljdoc/render/rich_text_test.clj, test/cljdoc/util/ns_tree_test.clj
We now only render wikilinks as links when:
- wikilink rendering is enabled (i.e. for docstrings only)
- when the text inside the wikilink resolves to an existing namespace
or var in the library
- wikilink syntax does not include text, ex. [[my.ns/var|text]] will
render as self
Although we make use of elements of the flexmark wikilink extension
we no longer register it as an extension.
One could argue that we should just write our own flexmark extension
for cljdoc wikilinks, but this seems to be working for the time being.
Closes #507
=> Only render [[wikilinks]] when appropriate

deps.edn, src/cljdoc/analysis/service.clj, src/cljdoc/server/api.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/ingest.clj, src/cljdoc/storage/sqlite_impl.clj
The goal is to avoid future confusion, includes updating of bindings and
variable names, etc.
Closes #540
=> Analysis is now saved to cljdoc-analysis.edn

src/cljdoc/analysis/service.clj, src/cljdoc/git_repo.clj, src/cljdoc/server/api.clj
Use the cljdoc-analyzer's new RELEASE git tag to automatically select
its current production release.
We continue to log the associated long sha as the version.
Includes minor rework to local analysis.
Build kick off now returns map with future proc instead of future map.
This allows kick off caller to inspect return of kick off for
returned analyzer version.
Closes #549
=> Automatically select cljdoc-analyzer release

src/cljdoc/analysis/service.clj, src/cljdoc/server/api.clj
When cljdoc gives up waiting for CircleCI job to complete API analysis,
indicate a timeout error instead of a generic failure.
Closes #446
Closes #456
=> Distinguish analysis timeout error

deps.edn, package-lock.json, package.json, resources/asset-deps.edn, src/cljdoc/server/system.clj
Highlights:
- Clojure v1.11
- Lucene v9.1.0 saves to new index-lucene91 dir, lucene 9.0 index is not
compatible with lucene 9.1. Can delete index-lucene9 at some later date.
- Address npm and jackson CVEs
=> maint: update deps

src/cljdoc/render/sidebar.clj
Now also handles case where user is looking at a SNAPSHOT release
that might be newer than the current release.
Closes #563
=> Generalize text informing user of current release

js/svg.d.ts
Allow importing of svg files in tsx files such that they can be passed to the img tsx tag as a src like so:
```
import cactus from "../resources/public/cactus.svg";
```
This will make the rendered image tag have a src of something like `/cactus.df3ff92b.svg?1649565213993=`. The hash in the filename (`df3ff92b`) is derived from the file contents. This ensures that if the file content changes the url will change as well, avoiding image caching bugs. The query string includes the file modification time in milliseconds since epoch (`1649565213993`). I suspect that this helps avoid image caching bugs due to hash collisions.
=> Allow importing of svg files

src/cljdoc/server/pedestal.clj
Was formerly using stock clojure.core/memoize.
Switching to clojure.core.memoize/memo allows us to clear this cache
easily from a running REPL. Also automatically invoking clear when
pedestal is stopped.
Closes #574
=> A developer can now clear static resource cache

resources/public/cljdoc.css
The original, now ancient, issue showed some renderings that also
changed the formatting of the table of contents list. I decided against
this for the following reasons:
1. feature creep of the raised issue
2. would be inconsistent with a CommonMark manually hand-coded TOC
Closes #322
Before:
After:
=> Give adoc table of contents title some oomph

resources/public/cljdoc.css, src/cljdoc/render/rich_text.clj
This matches Markdown rendering behaviour.
And its handy.
Closes #599
=> Asciidoc headers are now rendered as links

resources/public/cljdoc.css
1011 days ago I raised an issue about AsciiDoc admonition styling.
There were some concerns in the issue about admonitions that contain
code. I was in deep back then. I seem to care less about such concerns
in this moment.
I think the styling changes here are an improvement, but would not be
offended if others felt differently.
Closes #327
Before:
After:
=> AsciiDoc admonitions styling

resources/public/cljdoc.css
Spacing now more resembles CommonMark list rendering.
Closes #603
=> Reduce spacing for AsciiDoc rendered lists

resources/public/cljdoc.css
AsciiDoc quotes now render like CommonMark quotes.
Styling also applied to quote attribution, an adoc-only feature of quotes.
Which also styled adoc verse block attribution (they were intertwingled).
Closes #606
Before:
After:
=> Style AsciiDoc quotes

resources/public/cljdoc.css
Definition list styling applied to both adoc and md.
The md format does not support a definition list syntax,
but if someone puts explicit `<dl><dt><dd>` in their article,
we'll style it.
Horizontal and q&a lists are adoc only constructs.
Closes #605
Before:
After:
(don't mind the `::` characters, they are typos in my test data)
=> Style definition, horizontal and q&a lists

resources/public/cljdoc.css
As always, much styling copped from AsciiDoctor's own asciidoctor.css
style sheet.
Did not want this block to look like an admonition so went with a white background.
Closes #607
=> Style AsciiDoc example block

resources/public/cljdoc.css, src/cljdoc/render/rich_text.clj, src/cljdoc/render/sanitize.clj
Mimicked adoc default styling for menu and & button.
Toned down kbd styling from adoc default css a bit.
Closes #613
md before:
md after:
adoc before:
adoc after:
=> Style kbd (md and adoc), menu & button (adoc)

js/single-docset-search.tsx
Right now if you click away from the search results box the search results stay visible. Instead we should hide the results when that is the case. This change fixes that.
=> Hide search results when you click away from the search box

js/single-docset-search.tsx, resources/test_data/searchset.edn, src/cljdoc/render/api_searchset.clj
No longer defaulting to generic parsing for markdown docs.
This means the lovely code that parses section headings out is now invoked.
Replaced generic doc parsing with asciidoc specific parsing.
So we now cover both our rendered document format types.
Now collecting text via JSoup nodes instead of JSoup elements.
JSoup elements skips text only nodes.
Bump the client side index version to force refetch.
Closes #592
=> Break down docset search by section headings

.circleci/config.yml
The build job is now a noop job that depends on:
- back-end-checks - does back end linty things
(teased out from old build job)
- front-end-checks - does front end linty things
(was formerly prettier job)
- test - runs cljdoc tests
(teased out from old build job)
- package - packages cljdoc for potential deployment
(teased out from old build job)
Potential benefits are:
1. shorten build time by running jobs in parallel (TBD)
2. separting build job out allows each individual job to fail separately,
giving us more more info. (Failing slower).
Other changes:
- front-end-checks now fails build if it fails
- moved entirely away from deprecated circleci docker images and now using their new cimg images.
(this sometimes required other changes)
- now also basing cache id on bb.edn where …
=> ci: tease out jobs, update docker images

.circleci/config.yml, doc/cljdoc-developer-technical-guide.adoc, js/library.ts, js/listselect.tsx, js/recent-doc-links.tsx, js/search.tsx, js/switcher.tsx, package-lock.json
Over time we started to reuse a CljdocProject type beyond its initially
designed scope. TypeScript got to the "huh?" point. Here's the fix I
applied:
1. Create a new Library interface (which only describes maven coordinate)
2. Replace general CljdocProject with specific but equivalent VisitedLibrary
which extends Library
3. Have SearchResult extend Library (otherwise unchanged)
4. Have ResultView use generics so that it is no longer tied to a specific
type/interface (it was tied to CljdocProject)
Switched from using TypeScript type to TypeScript interface to allow me to
express what I wanted to express.
I think this is ok: https://stackoverflow.com/a/65948871
Close https://github.com/cljdoc/cljdoc/issues/619
Also (because I was there):
- Moved redudant code to docsUri and project …
=> Fix TypeScript issue and add ci front end check

deps.edn
This turfs some ugly jackson dep overides. Yay!
But a bit of wack-a-mole because still need to override some
jackson for unilog.
=> maint: upgrade cheshire dep

bb.edn, deps.edn, script/helper/shell.clj, script/lint.clj
Bump our beloved clj-kondo.
Update lint script to follow clj-kondo docs re bringing in import configs.
=> maint: update clj-kondo and lint script

deps.edn
Of note:
- no longer need to compensate for CVE in sentry deps
=> maint: update clojure deps

.prettierrc.json, js/single-docset-search.tsx
When a project has a var that is a stop word, that var is unfindable in single docset search.
Ex: Go to https://cljdoc.org/d/babashka/fs/0.1.5/api/babashka.fs and type "with" to find "with-temp-dir". What's missing here? Oh darn, "with" is a stop-word.
Remove var names from stop-words for that individual index. Be sure to split on non-word characters so that we still match. Look and see if we can also match non-word characters since those are valid clojure var names (e.g. `<<`).
=> Try excluding var names from stop words for single docset search

js/switcher.tsx, package-lock.json, package.json
Of note:
- fuzzysort removed allowType option (we are unaffected, but were
explicitly setting it to false)
- resolves security issue with terser package
=> maint: bump npm deps

deps.edn
Removed explicit reference to slf4j-api, unilog now brings in
respectable logging deps, and slf4j 2.0.0 has some changes that require
all adapters (formerly binders, now service loaders) to be updated in
unison. So we'll wait for unilog to handle that.
=> maint: bump clojure deps

src/cljdoc/server/sitemap.clj
We exclude SNAPSHOT versions.
Libraries with only SNAPSHOT releases are excluded.
Although the order of URLs is not important to Google, we do now sort
our sitemap for a consistent result.
Closes #397
Closes #651
=> Sitemap now includes only latest official releases

doc/running-cljdoc-locally.adoc
Update docker ingest commands to use -Sforce.
This will force regeneration of .cpcache and will avoid
FileNotFoundExceptions for cljdoc deps that don't also happen to be in
the users local m2 repo.
Remove m2 repo volume mapping when launching server itself.
The docker image has everything it needs to run cljdoc, it does not
need the users local m2 repo.
Closes #654
=> docs: running locally with docker [skip ci]

doc/userguide/for-library-authors.adoc, js/cljdoc.ts, js/index.tsx, src/cljdoc/render/articles.clj, src/cljdoc/render/sidebar.clj
Formerly we were suggesting to the reader that they might want
to glance at our Articles docs. This messaging always appeared when a
library did not have more than readme and/or changelog articles.
This did not make a ton of sense and was a bit noisy/wordy.
As raised in the issue, we now assume the library author does not need
a tip if we have found their project's cljdoc.edn config.
We instead now offer a click-able "tip" in the articles header.
It is noticeable but also subtle.
When clicked, the tip shows tip content to the user.
The tip appears when:
- there is no cljdoc.edn and we've auto-discovered articles
- there are no articles because scm cannot be found
- there are no articles in a found scm
To make this work, we've move all articles under the articles header.
Formerly readme …
=> Rework library articles tips

resources/public/cljdoc.css
Adds an underline to links within docs.
The link on the left is being hovered over.
=> Give doc links a nice hover underline

src/cljdoc/render/index_pages.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/search/api.clj, src/cljdoc/server/search/search.clj, test/cljdoc/server/search/api_test.clj
There was an old todo that I meant to address when updating Lucene
support. Finally got to it.
When listing versions of an artifact, the cljdoc website shows built
versions. A while ago, to support the Dash offline reader, cljdoc added in
support for returning all known versions from maven and clojars.
Before this change, we cached available artifacts and their versions in
memory. The old @holyjak todo was to not bother with the cache and just
hit our Lucene index directly.
My tests indicate that this works out fine when searching for a specific
artifact or artifact group. When returning all known artifacts, the request is
heavy but most time is spent in processing the result, so seems fine too.
Although Dash will request these versions as json, our website has
support to display them as …
=> Search lucene directly for Dash versions api calls

src/cljdoc/server/ingest.clj
It relies on :commit in git analysis result which I erroneously turfed thinking it was unused.
Addendum to #31
=> Correct build log reporting

deps.edn, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/server/system.clj, src/cljdoc/util/fixref.clj
Cool, it now lints for cases where we aren't using the ns aliases we set up. 
Address findings.
=> maint: bump clj-kondo

deps.edn
we no longer need the jackson override to overcome CVE, unilog bumped jackson
=> maint: bump unilog

.circleci/config.yml
I am getting:
class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode
when downloading deps via Clojure CLI.
This is supposed to be a fixed issue, so I'll to move to the current release of Clojure to and see if that fixes things.
Also, CircleCI image includes babashka, but a stale version, so let's use latest and greatest.
Also, I've learned that we can use YAML aliases with CircleCI configuration, so I've incorporated those to make our config a little less copy/paste.
=> maint ci: use current clojure bb, yaml aliases

modules/deploy/src/cljdoc/deploy.clj
It can take a while for a pushed docker image to become visible on docker hub. I have noticed sporadic failures in the past.
On 2022-10-17 I was seeing repeated failures, one case taking 20m for a pushed tag to appear. I assume this was just a bad day for docker hub.
Start with what seems to be reasonable retry timeout of 3m with 2s interval.
includes: rework of wait-until fn to do more logging
=> ci: deploy: retry check for cljdoc docker tag

modules/deploy/deps.edn, modules/deploy/src/cljdoc/deploy.clj, script/outdated.clj
While diagnosing a deploy issue, I stumbled on some ancient deps for our deploy module. I switched from clj-http to clj-http-lite (because we use that in cljdoc itself, and we have not need for the beefier clj-http).
It all seems good, but will tweak based on success (or lack thereof) of next deploy.
Also added the deploy module to our `bb outdated` check.
=> maint: bump deploy module deps

deps.edn, tests.edn
of note: jgit
also: turn off kaocha notifier plugin, it does not work well on all platforms and is more of a user preference.
=> maint: bump clj deps

js/single-docset-search.tsx
Doc set search input width was overflowing and getting clipped on Linux and Windows platforms.
(For whatever reason, this was not happening on macOS).
Setting the input element width to 100 ensures it will be sized to its parent width.
Closes #698
=> css: restrict doc set search input width

src/cljdoc/platforms.clj
I've seen a lot of these exceptions being thrown and probably we shouldn't just break everything when something like `:deprecated` is different on clojure than clojurescript.
Seems that this stems from the usage of a `defalias` helper in the [affected library](https://github.com/ptaoussanis/encore/blob/89e09ac5656369578cbd30ab0283c1bd3fe80c45/src/taoensso/encore.cljc#L4979).
=> dont fail hard on platform differences

src/cljdoc/render.clj, src/cljdoc/render/api.clj
Existing var annotations are `cljs`, `cljs` and `clj/s`.
A new `clj/s≠` annotation is used for vars where there are differences in docstring, arglists and/or protocol members across platforms.
When differences exist, this new annotation is always shown in the var index regardless of dominant platforms.
Var annotations now always shown for all vars in var detail view, including protocol members.
There is no var index for offline docs, but var detail is affected. Will verify macOS Dash app is ok with this after deploy and adjust as necessary.
Closes #702
=> Indicate when a var has diffs across platforms

src/cljdoc/render/api_searchset.clj
If an author hand codes a header in html, it must
conform to the html generated from a markdown header.
Also: dropped the expectation of the cljdoc inserted md-anchor class.
Fixes null pointer exception for selmer lib when generating docset server-side to support client side search.
Closes #712
=> Skip problematic md headers for docset search

resources/migrations/012-add-retry-count-to-releases.down.sql, resources/migrations/012-add-retry-count-to-releases.up.sql, src/cljdoc/render/build_log.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/release_monitor.clj, src/cljdoc/server/system.clj, src/cljdoc/util/repositories.clj
I have learned that that artifacts listed by clojars sometimes do not resolve. One example is an artifact with a version of just "SNAPSHOT".
The cljdoc release monitor pings clojars for new releases and will endlessly retry these unresolvable, but listed, artifacts.
There are not many cases of these, but they do generate exceptions which is confusing noise for the cljdoc devops team.
There are other flows that trigger doc builds, this change is limited to the release monitor flow. This is the one generating the logging noise.
The release monitor now does a pre-check.
The pre-check tries to resolve the artifact, if resolve returns
- 200 - good to attempt a build
- 404 - create and immediately fail build with listed-artifact-not-found
- else - requeue release, if after 10 tries, still no …
=> Handle case: listed artifact does not resolve

js/switcher.tsx, src/cljdoc/render/error.clj, src/cljdoc/render/layout.clj, src/cljdoc/server/api.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/util/repositories.clj, src/cljdoc/util/sqlite_cache.clj, test/cljdoc/util/repositories_test.clj, test/cljdoc/util/sqlite_cache_test.clj
Previously we only presented a page not found 404 page when a route was not found.
When a library was not we'd throw and generate a 500 error.
A library not found error happens when a user directly manipulates or scripts a cljdoc URL. You'd think this would be rare, but our logs tells us it happens enough to be worthy of addressing.
This change adjusts our existing 404 page to:
- provide a link back to the cljdoc home page (was missing)
- include some details of the library that was not found
Impacts:
- adjusted client side visit history/switcher to ignore library 404 errors
- adjusted pom db caching (in cache.db) to never cache pom that is not found (we were previously throwing on pom not found). Adjusted tests accordingly.
Closes #720
=> When library not found present 404 page

src/cljdoc/server/pedestal.clj
Was 500, now returning generic page not found
=> 404 for builds/id not found

src/cljdoc/render/api.clj
Was reporting invalid arglists for vars with nil arglists, but that's silly, not all vars have arglists.
Addendum to #728
=> Fix: not all vars have arglists

js/hljs-merge-plugin.ts, js/index.tsx, js/window.d.ts, resources/asset-deps.edn, src/cljdoc/render/layout.clj
I was on the fence about this one as v11 removed auto-merging of HTML into formatted blocks. This feature supports AsciiDoc callouts. See: https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/ if you need a reminder as to what these are.
After more carefully reading over highlightjs/highlight.js#2889, I realized maybe it wouldn't be very difficult to simply re-introduce the feature. The issue even includes a complete JavaScript code example to do so.
I did my naive best to transcribe the sample JavaScript to TypeScript (which even caught a couple of minor issues).
It took me some time to figure out a way to expose the TypeScript function to our layout page. Parcel.js used to provide a --global option to support this use case, but that feature was removed.
In the end I just …
=> Upgrade to highlight.js v11

.clj-kondo/config.edn, .clj-kondo/nubank/matcher-combinators/config.edn, deps.edn, package-lock.json, package.json
of note:
- matcher-combinators includes a clj-kondo config, so delete ours and use theirs
=> maint: bump deps

src/cljdoc/util/scm.clj, test/cljdoc/util/scm_test.clj
This fixes an issue with extra segments in the SCM URL field:
<scm>
<url>https://github.com/pitch-io/uix/tree/master/core</url>
<tag>33de62e1f0425aaeb5249a589f0cc5c98a848f0f</tag>
<connection></connection>
<developerConnection></developerConnection>
</scm>
Would previously attempt to clone from `git@github.com:pitch-io/uix/tree/master/core.git`
Leading to a `clone-failed` error in [builds like this one](https://cljdoc.org/builds/65965).
With this change we do not allow more than 2 segments after the domain which I think should work with all SCM services we integrate with.
=> remove superflouos segments from http uris

src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj
I'm spiking on an experiment to expose the cache-bundle via the API in order decouple the frontend and the backend. This should enable me (and others) to experiment with different frontends a little more. I'm not sure on the naming here or if there's any formatting we'd like to apply to this data before sending it back but this is the raw, simple version.
```
❯ curl 'http://localhost:8000/api/docsets/babashka/fs/0.1.6' | gron | head -10
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 30610    0 30610    0     0  1386k      0 --:--:-- --:--:-- --:--:-- 1992k
json = {};
json.defs = [];
json.defs[0] = {};
json.defs[0].arglists = [];
json.defs[0].arglists[0] = [];
json.defs[0].arglists[0][0] = "joined-paths"; …
```
=> Expose cache-bundle via the API

src/cljdoc/render/build_log.clj
The build log was trying to distinguish a version tag vs a sha based on length only and then truncating a sha to a short-sha.
This is too naive and is truncating version tags longer than 8 chars.
For now we'll just blurp out the whole version/sha. To me this looks fine and is acceptable for a low traffic web page.
If we ever want to revisit, we'll have cljdoc store the necessary info in the build log so the render code does not have to make naive guesses.
Closes #757
=> build log: don't attempt to truncate to short sha

deps.edn
Take advantage of cool new antq feature to ignore jetty 10.x and 11.x release streams.
=> maint: bump antq

deps.edn, package-lock.json, package.json, src/cljdoc/server/system.clj
Now automatically including current lucene version in lucene index dir name. This avoids me forgetting to do this manually when bumping lucene.
Bumping flexmark, as expected (but checked anyway), did not fix https://github.com/vsch/flexmark-java/issues/551
=> maint: bump deps + auto lucene dir

deps.edn, resources/test_data/cache_bundle.edn, resources/test_data/searchset.edn
This allowed us to turf jruby dep to overcome CVE.
But also:
Ascidoctorj bumped asciidoctor from v2.0.18 to v2.0.20. This included a bug fix for passthrough processing.
Seems that rewrite-clj docs for api diffs has some passthrough adoc that only happened to work but was never supported.
I confirmed this with the very helpful mojavelinux on asciidoctor zulip chat:
https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/complex-ish.20passthrough.20is.20rendering.20differently.20in.202.2E0.2E20/near/363769467
Our searchset tests expectations needed to be regenerated because the html generated by adoc for rewrite-clj is now different.
If I remember, I'll come back and bump rewrite-clj here after addressing adoc nonsense there.
=> maint: bump asciidoctorj

deps.edn
`+` in path portion of URL is handled differently and causing failures.
See: https://github.com/cljdoc/cljdoc/issues/764#issuecomment-1579091110
=> downgrade pedestal

deps.edn, src/cljdoc/server/pedestal.clj, test/cljdoc/integration_test.clj
Notes for future me:
- I missed pedestal breaking change.
- The pedestal project had described releases under GitHub releases, but for 0.6.0 they have not. I assumed I was reading about the current release when I was reading about an old release.
- Also not totally obvious: when you do find 0.6.0 described in the pedestal changelog file, it is marked as "unreleased" even though a beta has been released.
Now adapting to breaking change by setting `:path-params-decoder` to `nil` on server creation. This fixes our `+` in URL issue and closes #764.
Since `+` in URLs have now bitten us twice, added an explicit integration test.
=> Bump pedestal back to 0.6.0-beta-2

doc/userguide/for-library-authors.adoc, src/cljdoc/user_config.clj
While looking at cljdoc code for #779 I scratched my head for a long while wondering why cljdoc's `cljdoc.user-config` ns is looking up subprojects in a `cljdoc.edn` config.
I searched a backup of the production db for any libraries that might have a `cljdoc.edn` using this config pattern.
I found only one: clj-otel.
The scenario is one git repository producing multiple artifacts. And you want to document to artifacts separately on cljdoc.
I have shared my new understanding in the library author's guide. And added a note to the `cljdoc.user-config` ns.
=> author docs: updates on module configuration

doc/userguide/for-library-authors.adoc, src/cljdoc/analysis/git.clj, src/cljdoc/render.clj, src/cljdoc/render/api.clj, src/cljdoc/render/offline.clj, src/cljdoc/spec/cache_bundle.clj, src/cljdoc/storage/sqlite_impl.clj, src/cljdoc/user_config.clj, test/cljdoc/analysis/git_test.clj
Library authors can now specify `:cljdoc/docstring-format :plaintext` in their git hosted `doc/cljdoc.edn` config file.
Also: tweaked user-config a tad, simplified the code that chooses module library artifact config. I think it should be easier to grok now.
Closes #779
=> Support displaying docstrings as plaintext only

.clj-kondo/config.edn, .clj-kondo/http-kit/http-kit/config.edn, .clj-kondo/http-kit/http-kit/httpkit/with_channel.clj, .clj-kondo/taoensso/encore/config.edn, .clj-kondo/taoensso/encore/taoensso/encore.clj, deps.edn, tests.edn
Changed test reporter for developer run tests to document reporter. This lists each individual test as it is being run which, in my mind, provides much better feedback.
Add new .clj-kondo library lint exports downloaded by clj-kondo.
=> maint: bump deps, change test reporter

js/cljdoc.ts, js/index.tsx, src/cljdoc/render/api.clj, src/cljdoc/render/offline.clj
We already had raw<->formatted toggle for var docstrings. This adds same for namespace docstrings.
Also: noticed toggle had no effect for downloaded offline var docstrings, so fixed that.
Also: noticed `cljdoc/docstring-format :plaintext` had no effect for offline docs, so fixed that too.
Closes #782
=> Add docstring format toggle to namespace docs

js/hljs-copybutton-plugin.ts, js/index.tsx, js/window.d.ts, resources/public/cljdoc.css, src/cljdoc/render/layout.clj
I had a look around for an existing library and found https://github.com/arronhunt/highlightjs-copy.
It seems good, but maybe does more than we'd like and also perhaps has some unresolved issues.
So, taking some inspriaton from the above,  I coded up something simpler for cljdoc.
These UI things are subjective, but I think this is a reasonable first cut.
Closes #786
=> Add copy button to code blocks

resources/public/cljdoc.css
We might have strayed from our Tachyons pallette here a bit, but I think it was worth making the adoc IMPORTANT admonition look less garish.
Closes #791
=> De-garish AsciiDoc IMPORTANT admonition

.circleci/config.yml, bb.edn, build.clj, build_shared.clj, deps.edn, doc/cljdoc-developer-technical-guide.adoc, script/package.clj, src/cljdoc/render/FixupImgRefLinksExtension.java, src/cljdoc/render/FixupImgRefLinksPostProcessor.java, src/cljdoc/render/rich_text.clj, test/cljdoc/render/rich_text_test.clj
We use Flexmark to render markdown.
Add a custom Flexmark post processor to fixup Flexmark AST for a link-ref whose body is an image-ref.
Closes #743
=> Work around Flexmark link-ref image-ref bug

doc/userguide/for-library-authors.adoc
Some elaborations around API links.
Closes #799
=> docs: lib author's guide

js/cljdoc.ts, js/index.tsx, js/recent-doc-links.tsx, js/single-docset-search.tsx, src/cljdoc/render/articles.clj, src/cljdoc/render/home.clj, src/cljdoc/render/index_pages.clj, src/cljdoc/render/layout.clj, src/cljdoc/render/search.clj, src/cljdoc/render/searchset_search.clj, src/cljdoc/render/sidebar.clj
A library author can specify link anchors in their articles. 
These are rendered in HTML as `id` attributes.
Cljdoc was, in various places, also using HTML `id` attributes for various things.
Some ids were common words, and therefore more likely to conflict, like `version` and `project`.
This PR moves these cljdoc `id` attributes to `data-id` attributes to avoid potential conflict with user content. (A viable alternative would have been to use class names, but I felt this made it clearer these ids are all for use from JavaScript).
There remains a few `id` attributes generated by the asciidoc converter, (ex. `toc` and `toctitle`) I've not bothered to address these at this time.
Closes #803
=> Avoid using HTML id attribute to avoid conflicts with user content

resources/public/cljdoc.css
Don't see any need to format this case differently, if we learn differently, we'll adapt.
Closes #805
=> fix: adoc style for only-child code elem in table

resources/public/cljdoc.css
This reverts commit daec34a78bfeb008c636fa0d8fa6143dcd62c204.
Closes #805
=> Revert "fix: adoc style for only-child code elem in table"

js/cljdoc.ts, js/index.tsx, src/cljdoc/render/articles.clj
Switched from localStorage to sessionStorage for scroll state. I think being more ephemeral here is the better way to go.
Noticed that restored scroll position was a bit off every time. Waiting for the dom to load fixed this jitter.
Now saving scroll state when a user clicks on a sidebar item. If that state is present and is for the same doc lib/version on load, then we restore the scroll pos.
Otherwise, if the selected sidebar item is out of view, we scroll to it. This supports things like bookmarks.
Noticed that style for highlighting of article and api items were different. They are now both a tachyons `b`.
Because our docset search input is effectively part of the sidebar and scrolls with the sidebar, I opted to not to do any automatic scrolling when the user selects a docset search …
=> Fixups for sidebar scroll pos save/restore

.eslintignore, .eslintrc, js/single-docset-search.tsx, package-lock.json, package.json
Searching a single docset is a client-side feature. It now supports searching for text that contains punctuation.
This can be helpful when searching for vars and/or namespaces which can contain punctuation.
Highlights of changes:
- strongly favour exact match of terms with punctuation but also match on subterms. For example a search for `cloure.core.test` would strongly prefer an exact match but also match on terms `clojure`, `core` and `test`.
- turn off stemming support, I think we are ok without it. We already do expansion matching (i.e. `ab` matches `abc` `abracadabra`, etc), and stemming might be less helpful for source code elements.
- turn off stop words. Stop words are normally interesting for prose, but for code, we probably don't want to exclude common words.
- turn off trimmer, …
=> Support punctuation in single docset search terms

resources/public/cljdoc.css, src/cljdoc/doc_tree.clj, src/cljdoc/render/rich_text.clj
Clojure's README is readme.txt and uses plain text.
I don't know of any other library that uses .txt for articles, but this one is important enough to add the necessary support.
Closes #819
=> Add support for plaintext .txt articles

.clj-kondo/com.github.seancorfield/next.jdbc/config.edn, .clj-kondo/com.github.seancorfield/next.jdbc/hooks/com/github/seancorfield/next_jdbc.clj_kondo, deps.edn, resources/migrations/010_convert_builds_error_info_from_exception_to_data.clj, src/cljdoc/config.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/clojars_stats.clj, src/cljdoc/server/release_monitor.clj, src/cljdoc/storage/sqlite_impl.clj, src/cljdoc/util/sqlite_cache.clj, test/cljdoc/util/sqlite_cache_test.clj
The intent is the same behaviour as before.
To avoid too much rework, asked next.jdbc to return clojure.java.jdbc compatible result sets with `:builder-fn rs/as-unqualified-maps` option.
Opted to not ask next.jdbc to use JDBC's `Statement` `getGeneratedKeys`. We were transparently taking advantage of this in clojure.java.jdbc. But this method was deprecated by sqlite-jdbc because it is unreliable. It was removed in v3.43.0.0 (which we'll upgrade to separately).
We instead rely on SQLite's RETURNING syntax to return generated keys. This was only needed when inserting a new build log entry.
Next.jdbc does not have funtions to abstract the creation of tables, so simply generated the necessary SQL to create our cache table.
I took advantage of next.jdbc sql sugar syntaxes when the change was …
=> Migrate from clojure.java.jdbc to next.jdbc

doc/userguide/for-library-authors.adoc, src/cljdoc/doc_tree.clj, src/cljdoc/spec/cache_bundle.clj, src/cljdoc/storage/sqlite_impl.clj, test/cljdoc/doc_tree_test.clj
Any `.txt` articles in doc/ or docs/ dir are now appropriately processed. Title is inferred from the article filename.
Closes #830
=> Plaintext article title is inferred from filename

src/cljdoc/server/pedestal.clj, src/cljdoc/util/fixref.clj
Particularly the artifact loading logs are very verbose.
=> remove some noisy and not all that useful logs

bb.edn, build.clj, deps.edn, script/docker_entrypoint.clj, script/lint.clj
Use new "bb print-deps" for full list of bb dependencies including built-ins. Tack this onto clojure deps when calculating classpath for lint cache build.
To support Windows, with its limited command-line length, move to building cache programmatically in clojure in build.clj.
This is not perfect, if a bb dep version is older than a clojure dep version, we'll end up using the older dep, but it is better than before and unlikely to cause issues.
=> lint: tweak clojure vs bb deps

resources/public/cljdoc.css
Margin bottom spacing transcribed from:
https://github.com/asciidoctor/asciidoctor/blob/be27047cad5de15ab53513be894f3a423f5734b0/src/stylesheets/asciidoctor.css#L1112-L1119
Closes #842
=> Fix vertical spacing for images (and other) blocks

js/hljs-copybutton-plugin.ts
We hook in our copy button via a highlight.js plugin.
Switching from `after:highlightElement` to `before:highlightElement` and
grabbing the innerText of the element seems to have done the trick.
Closes https://github.com/cljdoc/cljdoc/issues/844
=> fix: exclude adoc callouts from code block copy

script/docker_entrypoint.clj
Not the most elegant solution but at least this should reduce downtime while the OOM issue remains undiagnosed :) 
https://stackoverflow.com/questions/30530082/how-can-i-restart-jvm-on-outofmemoryerror-after-making-a-heap-dump
=> Exit on OutOfMemory Exceptions

script/docker_entrypoint.clj
Our docker jvm max heap is reported as:
```
$ nomad alloc logs -stderr 488e4d6d
VM settings:
Max. Heap Size (Estimated): 386.69M
Using VM: OpenJDK 64-Bit Server VM
```
Our current docker container is 1600mb.
The default ram percentage used by the jvm is 25% or ~400mb. This is a conservative default.
As far as I remember, we don't have much else going on in our cljdoc docker container. So let's try bumping the ram percentage to 75% or ~1200mb.
=> docker: increase max jvm heap size

deps.edn, src/cljdoc/server/search/api.clj
I had reverted bumping lucence but I don't think it was actually problematic.
I did notice the throwing of exceptions when searching an non-existent lucene index, so we now ensure one always exists for searches.
=> maint: re-bump lucene

.circleci/config.yml
The CircleCI clojure convenience image seems to not get much love anymore, it is still at JDK 17, for example.
The clojure docker image does get love, so we'll use it instead.
=> ci: switch to clojure docker image for JDK 21

.circleci/config.yml
Our clojure docker image user is sudo, but the image we use to publish to docker requires the sudo command.
=> ci: sudo bb install when necessary

.circleci/config.yml
CircleCI now prefers we use "default" instead of specific machine image tags.
This means we might need to adapt when CircleCI updates the underlying machine image but... makes us a better CircleCI citizen? And means we'll not need to periodically update this config.
Also addressed security warning about docker login and moved login step to where it is actually needed.
Closes #871
=> ci: address machine deprecation warning

.circleci/config.yml, bb.edn, doc/cljdoc-developer-technical-guide.adoc, eslint.config.mjs, js/cljdoc.ts, js/doctree.ts, js/hljs-merge-plugin.ts, js/index.tsx, js/listselect.tsx, js/mobile.tsx, js/navigator.tsx, js/recent-doc-links.tsx, js/search.tsx, js/single-docset-search.tsx, js/switcher.tsx, js/window.d.ts, package-lock.json, package.json, tsconfig.json
Our front end is written in TypeScript, but not many of us know TypeScript very well.
A linter may help us stay in line.
I had added eslint deps a while back, but this PR addresses (or ignores in a few cases) all eslint findings.
The new bb task `eslint` is now also invoked with CI front-end checks.
=> Start using eslint

doc/cljdoc-developer-technical-guide.adoc, src/cljdoc/render.clj, src/cljdoc/render/home.clj, src/cljdoc/render/layout.clj
This adds improved link preview images for documentation on cljdoc, powered by [Dynogee](https://dynogee.com?ref=cljdoc). Happy to provide this to cljdoc for free (would potentially ask for a backlink at some point). 
This is the default / first article in the doc tree, instead of showing "Readme" or "Home" it shows the description according to `pom.xml`
Other article pages show the title of the article according to the doctree
Integrates namespace name, and a snippet of the ns docstring
In Slack these images would be displayed as below (note that I doctored that screenshot a bit, the domain, page title etc would be cljdoc's)
=> Improve link previews

src/cljdoc/render.clj
PR #884 did not expect ns-data to be nil for parent ns with no vars, which resulted in a throw, which resulted in a 500 error returned to cljdoc site user.
Closes #885
=> fix 500 error when clicking parent ns

src/cljdoc/render.clj
I'm realizing the version creates a bit of a combinatorial explosion for generated images... and it probably doesn't add all that much value. So to slightly reduce the number of images Dynogee generates for cljdoc I'd remove the version from the image.
=> don't render project version in og images

modules/nvd-scan/deps.edn, modules/nvd-scan/nvd-suppressions.xml
Deps check 10.0.2 is a mandatory update.
Simplify suppression rules for jetty toolchain libs.
=> ops: nvd-scan: rebump deps check [skip ci]

ops/exoscale/deploy/resources/traefik.toml
tell traefik to use non-staging acme endpoint
=> ops: enable prod ssl certs

ops/exoscale/deploy/resources/cljdoc.jobspec.edn, script/docker_entrypoint.clj
Try separate ports for jmx and rmi and try exposing to static values that match de facto conventions.
=> more tweaks for visualvm

ops/exoscale/deploy/resources/cljdoc.jobspec.edn
ChatGTP can steer a person in odd directions, it is ReservedPorts, not StaticPorts.
=> ops: jmx for visualvm more tweaks

ops/exoscale/deploy/resources/cljdoc.jobspec.edn, script/docker_entrypoint.clj
Jmx (or maybe rmi?) is a nasty little thing to configure. Some folks say setting both ports to the same tells the jvm to absolutely only use a single port for all comms.
=> ops: visualvm tweaks

.circleci/config.yml
Node failed to install last CI run, let's see if bumping node orb helps.
=> ci: bump circleci node orb

ops/exoscale/deploy/src/cljdoc/deploy.clj
In local testing, I found that nomad can return an evaluation in `pending` `State`. The `DeploymentID` is not populated until the evaluation is in `complete` `State`. So we now wait for the evaluation to complete before proceeding.
=> ops: deploy: wait for nomad evaluation to complete

ops/exoscale/deploy/resources/cljdoc.jobspec.edn, ops/exoscale/deploy/resources/traefik.edn, ops/exoscale/deploy/src/cljdoc/deploy.clj, ops/nomad.sh, script/docker_entrypoint.clj
This was a confusing slog!
Visualvm talks to jmx over rmi.
The RMI handshake starts off with a request to an RMI registry that returns the hostname on which to continue the session.
A docker container deployed by nomad is bound to the host IP. I haven't found a way around that. It thing that for normal nomad usage this is probably reasonable, our single node usage of nomad is unconventional.
The only way I can see to expose a nomad docker deployed cljdoc server port is through traefik. This is a bit non-intuitive to me because I saw traefik as our public front end, not a private ops front-end.
Traefik does support routing tcp traffic.
Docs, as usual, are on the brief side.
But I stumbled on the correct incantation.
So what we have is:
- cljdoc server jvm process enables jmx on port 9010 …
=> ops: support visualvm -> cljdoc server

src/cljdoc/render/build_log.clj, src/cljdoc/server/build_log.clj, src/cljdoc/server/pedestal.clj, src/cljdoc/server/routes.clj, src/cljdoc/util/datetime.clj, test/cljdoc/util/datetime_test.clj
The builds page now recognizes an optional `?end-date=2024-03-02` query string.
We now show the last 5 days of builds instead of maybe the last 5 days of builds for the last 100 builds.
Builds page now has a header for each day.
We now recognize that some days might have no builds.
All of the above is to support dev/ops and will help when verifying #561 work locally against production.
=> builds page: add from-date, show date headers

src/cljdoc/server/search/maven_central.clj, src/cljdoc/server/search/search.clj
Clojure's `tools.build` moved from group `org.clojure` to `io.github.clojure` a while back.
Allow docs for the lib at the new coordinates to be built.
Give the legacy coordinates a slight down-boost to favour the new coordinates in search.
Closes todo 4 from #901
=> Allow docs to be built for io.github.clojure/tools.build

.clj-kondo/imports/hiccup/hiccup/config.edn, .clj-kondo/imports/hiccup/hiccup/hiccup/hooks.clj
This one was added by clojure-lsp which I think imports all of `bb print-deps`, which seems like good thing to do.
=> dev: add missing clj-kondo imports

bb.edn
Automatically compile-js where appropriate.
Remove unnecessary redundant deps-js in some cases.
=> dev: review/adjust bb task dependencies

ops/exoscale/deploy/resources/cljdoc.jobspec.edn, ops/exoscale/deploy/src/cljdoc/deploy.clj
Replace good `#nomad/seconds 1800` with even better `#nomad/duration 30m` for at-a-glance human-friendly durations.
Can express multiple units, e.g. 3m30s and decimal values, e.g 3.5m.
=> ops: human friendly durations for nomad job spec

ops/exoscale/deploy/resources/cljdoc.jobspec.edn
Martin received a "certificate expire notice" email from letsencrypt. If we look at cljdoc ssl certs they are slated to expire on Feb 6. Which matches the email.
Does it mean that traefik is not auto-renewing our certs? I don't see anything in the traefik.log.
If I read https://letsencrypt.org/docs/expiration-emails/, maybe this is nothing to worry about?
Let's bump traefik to see if that has any effect.
=> ops: bump traefik

ops/exoscale/deploy/resources/cljdoc.jobspec.edn
Without this letsencrypt won't be able to automatically renew our ssl certs.
=> ops: traefik: allow ssl cert renewal request

deps.edn, resources/config.edn
Looks aws team introduced a bug in 2.30.9 that causes out of memory errors when uploading large files when the heap is relatively small.
Re-enable backup. It should work under this older version.
=> ops: downgrade aws sdk

modules/nvd-scan/deps.edn
To avoid dep churn, I've learned on other projects that it probably makes sense to use use latest deps for nvd scan.
[skip ci]
=> ops: tweak nvd-scan to always use latest deps

bb.edn
Very cool. Current output is:
```
[ TASK unused-deps ]-------------------------------------------------------------
Dependencies that do not seem to be referenced by code
NOTE: some unused deps are overrides to bring in later version of a dep to compensate for bugs or CVEs
[ch.qos.logback/logback-classic #:mvn{:version "1.5.18"}]
[dev.weavejester/ragtime #:mvn{:version "0.9.5"}]
[org.apache.lucene/lucene-queryparser #:mvn{:version "10.2.1"}]
[org.asciidoctor/asciidoctorj #:mvn{:version "3.0.0"}]
[org.eclipse.jetty/jetty-alpn-client #:mvn{:version "11.0.25"}]
[org.eclipse.jetty/jetty-alpn-server #:mvn{:version "11.0.25"}]
[org.eclipse.jetty/jetty-servlet #:mvn{:version "11.0.25"}]
[org.eclipse.jetty.http2/http2-server #:mvn{:version "11.0.25"}] …
```
=> dev: try out borkdude's new unused-deps

modules/nvd-scan/nvd-suppressions.xml
This should not be popping up, we use a later version of Clojure.
=> vulnerability scan: suppress CVE-2024-22871

front-end/src/cljdoc/client/namespace_scroll.cljs, front-end/src/cljdoc/client/single_docset_search.cljs, package-lock.json, package.json, src/cljdoc/render.clj, src/cljdoc/render/api.clj, src/cljdoc/render/api_searchset.clj, src/cljdoc/render/offline.clj, src/cljdoc/render/rich_text.clj, src/cljdoc/spec/searchset.clj
Notice `[[proto1-same2]]`, etc, are rendered as text.
Closes #707
I did not bother with the special case I described here: https://github.com/cljdoc/cljdoc/issues/707#issuecomment-1575368259. We can address it separately someday if the need arises.
=> Support prototype methods more

.clj-kondo/inline-configs/cljdoc.client.list_search.cljs/config.edn, front-end/src/cljdoc/client/docstring_toggler.cljs, front-end/src/cljdoc/client/dom.cljs, front-end/src/cljdoc/client/flow.cljs, front-end/src/cljdoc/client/hljs_copy_button_plugin.cljs, front-end/src/cljdoc/client/lib_search.cljs, front-end/src/cljdoc/client/lib_switcher.cljs, front-end/src/cljdoc/client/library.cljs, front-end/src/cljdoc/client/list_search.cljs, front-end/src/cljdoc/client/mobile.cljs, front-end/src/cljdoc/client/namespace_scroll.cljs, front-end/src/cljdoc/client/page.cljs, front-end/src/cljdoc/client/project_doc.cljs, front-end/src/cljdoc/client/recent_doc_links.cljs, front-end/src/cljdoc/client/single_docset_search.cljs, front-end/src/cljdoc/client/versions_form.cljs
On a tip from borkdude, I learned that `warn-on-lazy-reusage!` only needs to be called once from the entrypoint namespace.
=> squint: only need `warn-on-lazy-reusage!` once

front-end/src/cljdoc/client/list_search.cljs
Don't visually navigate to first item after item selection.
Rely on querying dom to determine input focus rather than trying to track it ourselves, and getting out sync with reality.
Git rid of 200ms hack.
We used to wait 200ms before closing list of items. We now instead explicitly handle the mouse down event.
Merge private sub-components into main component.
They all share data, and having them together made fixes much easier.
Closes #1104
=> ui: tweak lib search
