build.boot
ops/image/fedora-provision.sh
resources/build_log_migrations/001-create-builds-table.down.sql
resources/build_log_migrations/001-create-builds-table.up.sql
resources/config.edn
src/cljdoc/analysis/service.clj
src/cljdoc/config.clj
src/cljdoc/renderers/build_log.clj
src/cljdoc/renderers/common.clj
src/cljdoc/server/api.clj
src/cljdoc/server/build_log.clj
src/cljdoc/server/handler.clj
src/cljdoc/server/ingest.clj
src/cljdoc/server/system.clj

Fixes #14
Work in progress still but code review/feedback welcome.
This is what it looks like:

Better build logs

---

doc/userguide/for-library-authors.adoc

Asciidoc is best format
:trollface:

md->adoc for-library-authors

---

doc/userguide/for-library-authors.adoc

Just figured out why my copy-pasted config got messed up. :-)

Fix a typo

---

README.md
doc/running-cljdoc-locally.md
script/serve.sh

Workflow was mention before but this should clear things up for anyone new to this setup.

Mention clj REPL workflow

---

resources/public/cljdoc.js

traverse all available docstring blocks in toggleRaw

---

resources/public/search.js

Set autofocus property on search field

---

modules/analysis-runner/src/cljdoc/analysis/runner.clj
modules/shared-utils/src/cljdoc/util/deps.clj
modules/shared-utils/src/cljdoc/util/pom.clj

fixes https://github.com/cljdoc/cljdoc/issues/144

Issue144 analyzer doesn't fetch deps

---

src/cljdoc/render/build_log.clj
src/cljdoc/server/build_log.clj
src/cljdoc/server/pedestal.clj
src/cljdoc/util/datetime.clj
test/cljdoc/util_test.clj

Initial attempt at build analytics.
Looks something like this:
fixes #150

Add recent build analytics

---

js/listselect.js
js/search.js
js/switcher.js

Fixes #137 
Finally had some free time to finish off this issue:).
Now results are also highlighted on hover. Only thing left is to follow list selection with scroll.
Also changed selected element highlight color, as old one was a bit to dim in my opinion.

navigate search results using keys

---

src/cljdoc/render/error.clj

Add explicit 404 message on not-found page:

Improve 404 page

---

modules/analysis-runner/src/cljdoc/analysis/deps.clj

The original change was made to fix the build for compojure-api but maintaining a whitelist isn't really feasible and also didn't address the root cause in any meaningful way.
The root cause for the compojure-api build failure is captured in [TDEPS-46](https://dev.clojure.org/jira/browse/TDEPS-46) and hopefully will get addressed eventually.

revert to including scope test dependencies

---

doc/userguide/for-library-authors.adoc

Add information on formats supported by rich text renderer

---

doc/running-cljdoc-locally.md
modules/analysis-runner/src/cljdoc/analysis/runner.clj
src/cljdoc/analysis/service.clj
src/cljdoc/config.clj
src/cljdoc/render/layout.clj
src/cljdoc/server/api.clj
src/cljdoc/util/scm.clj

Fixed local build & updated the instructions

---

src/cljdoc/render/api.clj
src/cljdoc/render/articles.clj
src/cljdoc/render/layout.clj
src/cljdoc/renderers/html.clj

This addresses issue #99 
Fixes #99

Better separate Readme & Changelog from other articles #99

---

src/cljdoc/util/fixref.clj

Pretty self-explanatory, I guess, but there's more details on #192. This PR should solve that issue.

Add `nofollow` to external links

---

deps.edn
resources/config.edn
src/cljdoc/analysis/git.clj
src/cljdoc/config.clj
src/cljdoc/git_repo.clj
src/cljdoc/render/layout.clj
src/cljdoc/server/pedestal.clj
src/cljdoc/server/system.clj
src/cljdoc/util/scm.clj
test/cljdoc/util/scm_test.clj

See commits for details. Majority is improved support for different ways of providing SCM repository URIs (ssh vs http).

Various minor things

---

js/search.js

This PR addresses the issue with #271 . Thanks :)
fix #271

Remove unused scroll bar from search box

---

src/cljdoc/analysis/git.clj
src/cljdoc/doc_tree.clj
src/cljdoc/git_repo.clj
src/cljdoc/render.clj
src/cljdoc/render/articles.clj
test/cljdoc/doc_tree_test.clj

Inspired by [Daniel's tweet](https://twitter.com/danielwithmusic/status/1130559802680250372) and a two hour train ride with no internet. 
> 🐛 **Note:** Since this is something that is analysed and stored at build time it will only be available for builds done after this has been deployed.

feature documentation contributors at the end of articles

---

src/cljdoc/server/search/artifact_indexer.clj

Fix https://sentry.io/share/issue/afa0d0b8e99d44d3a1b100f3fd3dd2b6/
> llegalArgumentException: value must not be null
at artifact->doc line 126

Search: fix err when no origin

---

src/cljdoc/server/search/search.clj

The key change is that "SHOULD" is replaced with "MUST" regarding of the
occurrence of the search tokens, i.e. they all have to appear in a "document"
for it to match. Thus "metosin muunt" will only yield results that have both,
not those that have either (with the actual metosin/muuntaja way down the list).

Search: Require presence of all tokens in a longer query

---

resources/public/opensearch.xml
src/cljdoc/render/search.clj
src/cljdoc/server/pedestal.clj
src/cljdoc/server/pedestal_util.clj
src/cljdoc/server/routes.clj
src/cljdoc/server/search/api.clj
src/cljdoc/server/search/search.clj
src/cljdoc/server/system.clj

Inspired by PR #224 to provide suggestions for OpenSearch, e.g. in
Firefox, see https://developer.mozilla.org/en-US/docs/Web/OpenSearch

Search: suggestions API for OpenSearch

---

resources/migrations/008-add-error-info-column-to-builds.down.sql
resources/migrations/008-add-error-info-column-to-builds.up.sql
src/cljdoc/render/build_log.clj
src/cljdoc/server/api.clj
src/cljdoc/server/build_log.clj

Example:
Happy to make changes if needed, just let me know.

Show stacktrace for import errors; fixes #111

---

test/cljdoc/migration_test.clj

Add test for migration filenames

---

test/cljdoc/integration_test.clj

Exception no longer thrown after test run

---

doc/userguide/for-library-authors.adoc

(we also support other "changelog" names but lets keep it simple?)

for-library-authors: info about README, CHANGELOG

---

CONTRIBUTING.adoc

Add a Git Etiquette section to CONTRIBUTING doc

---

src/cljdoc/util/repositories.clj

Due to Clojars recently moving to S3 as a backing store for the
repository CDN at https://repo.clojars.org/, checking for the
existence of a directory for a group/id/version/ will no longer work
to confirm the existence of a version - non-existent paths will still
return a 200 with an empty index file.
This changes the existence logic to instead look for
group/id/version/maven-metadata.xml for SNAPSHOT versions, and
group/id/version/id-version.pom for non-SNAPSHOT versions. Those paths
*will* return 404 if the version does not exist, and this check should
work for any maven repository.
This also includes a little cleanup to use the new jar/pom-uri &
snapshot-version? helper fns.

Use full file path for exists checks

---

CONTRIBUTING.adoc

It's the smallest PR I ever done.

[DOC] Fix a tiny typography in CONTRIBUTING.adoc

---

deps.edn
src/cljdoc/server/pedestal.clj

Handle namespaces with special symbols in its name

---

src/cljdoc/server/api.clj

Closes #299 
PR is technically ready to merge. The question remains on my side, whether throwing an exception is actually in the spirit and intention of issue #299.

Throw exception when no namespace is found

---

modules/shared-utils/resources/hardcoded-projects-config.edn

A file was moved as part of day8/re-frame#528

Change the hardcoded config for re-frame

---

modules/shared-utils/resources/hardcoded-projects-config.edn

Moved to day8/re-frame in day8/re-frame#592
See [commit 18345ce](https://github.com/day8/re-frame/commit/18345ce09e046d72c5a3a42be6e09297460f6ebb)
Is there anything else that I need to do ?
Does this build off day8/re-frame master ?

Remove re-frame config

---

js/mobile.js
src/cljdoc/render/api.clj
src/cljdoc/render/build_log.clj
src/cljdoc/render/home.clj
src/cljdoc/render/index_pages.clj
src/cljdoc/render/layout.clj
src/cljdoc/render/offline.clj

Switch to clone of icon.now.sh

Provide quick fix for broken icons

---

src/cljdoc/render/home.clj
src/cljdoc/server/pedestal.clj

Ships #398, just a straightforward modification. Just passing the `q` parameter to the search form.

Support ?q=search-term query param on home page

---

src/cljdoc/render/rich_text.clj

Render AsciiDoc document titles

---

src/cljdoc/server/pedestal.clj

Because badgen.net will often (always?) return an error on the first
call to a badge it does not have in its cache, we introduce 1 retry
on failure after a 300ms sleep.
Also we now return a 503 to the client if we can't manage to get
a sucessful return from badgen.net. We were previously returning 200
on failure with a request to cache for 30 minutes, so a browser refresh
would not always retry to fetch a failed badge.
Fixes #422

Tweak calls to badge service

---

.circleci/config.yml
src/cljdoc/analysis/service.clj
test/cljdoc/integration_test.clj

Brings in some performance improvements.

Update cljdoc-analyzer dep

---

.clj-kondo/config.edn
.clj-kondo/lread/status-line/config.edn
bb.edn
deps.edn
doc/cljdoc-developer-technical-guide.adoc
doc/running-cljdoc-locally.adoc
resources/asset-deps.edn
script/helper/process.clj
script/outdated.clj

Checks and reports on:
- Clojure via antq
- JavaScript npm deps
- JavaScript CDN deps
Contributes to #333

Add a script to check for outdated dependencies

---

src/cljdoc/render/build_log.clj

Uses Wikipedia's capitalization rules for the button text:
https://titlecaseconverter.com/
Mimics the button format on the homepage and uses the styles suggested
in the issue.
Fixes #204 
Here's what it looks like when rendered on success:
**NOTE:** the red box was added by me in post, for emphasis

Make a clear next action on a successful build.

---

modules/shared-utils/resources/hardcoded-projects-config.edn
src/cljdoc/analysis/service.clj

@martinklepsch as discussed in Slack
Also update cljdoc-analyzer version, assuming a fast-forward, but that depends on cljdoc/cljdoc-analyzer#43. A rebase/squash/etc will necessitate updating the version in the PR.

Remove special handling for Manifold

---

ops/docker/Dockerfile
ops/docker/Makefile

Ugrade cljdoc web site docker container

---

deps.edn

We use antq to check for outdated deps

Bump antq deps

---

deps.edn
script/deploy-jar.sh

This reverts commit e4848cc38ae11ec4cf7ebdf5a4275f22ba9e3b3c.

Revert "maint: bump Clojure deps"

---

.circleci/config.yml

If I understand correctly, they now want us to explicitly reference a
modern image.
Closes #537

Respond to circleci image deprecation notice

---

deps.edn
src/cljdoc/analysis/service.clj

Bump cljdoc deps

---

doc/userguide/for-library-authors.adoc
src/cljdoc/analysis/git.clj
src/cljdoc/analysis/service.clj
src/cljdoc/render/build_log.clj
src/cljdoc/server/api.clj
src/cljdoc/server/ingest.clj
src/cljdoc/user_config.clj

Allow library authors to choose analysis platforms

---

src/cljdoc/render/sidebar.clj

Having no public API is not always an error

---

deps.edn
resources/asset-deps.edn

Add note on tachyons lack of release notes.

maint: upgrade deps

---

resources/asset-deps.edn

Add code block highlighting for AsciiDoc

---

src/cljdoc/render/home.clj

Add link to other Clojure resources from home page

---

src/cljdoc/server/search/search.clj

Was formerly showing latest release even if snapshot.
Now showing latest release followed by most current later snapshot
release (if any).
Closes #551

Include latest release when searching

---

src/cljdoc/server/search/search.clj

OpenSearch API suggestions no longer deemed URLs

---

deps.edn
src/cljdoc/server/search/search.clj

New linter has some good advice on placement of type hints!
Addressed.

deps: bump clj-kondo

---

resources/public/cljdoc.css

Style AsciiDoc sidebars

---

deps.edn

Of note:
- spootnik unilog updated their deps so we no longer need compensate

maint: clojure deps

---

deps.edn
ops/nvd-suppressions.xml

Override until new release of pedestal
Also: suppress nvd false positive for org.clojure/data-priority-map

maint: pedestal deps contain CVEs

---

doc/userguide/for-library-authors.adoc

docs: authors guide: maven repositories [skip ci]

---

js/search.tsx

Got some inspiration from single docset search.
Not sure why we don't grab query string q param directly from url in JS:
Server side render detects q param and populates data-input-value
attribute on search input elem. Maybe there's a good reason, did not change.
Also: when search input is cleared by user, now closing results.
Closes #586

Search term in url now populates search input

---

js/search.tsx

Fixes this issue I pointed out: https://github.com/cljdoc/cljdoc/pull/658#discussion_r960091385

Safe population of search query params

---

src/cljdoc/util/fixref.clj

Previously on multiple potential matches we chose first matching
`src/.*/<jarpath>`.
Now we prefer the shortest path that matches:
`.*/src(/main)?/<jarpath>`
And we also now log an error when we've found no reasonable
match.
Since this resolution is done at render time, affected projects do not
need a rebuild.
Fixes #663

Tweak rules for jar -> git sources correlation

---

src/cljdoc/server/pedestal.clj

fixed: accidentally broke dash json interface

---

.clj-kondo/config.edn
deps.edn

And turn on a few more linters.

maint: bump clj-kondo

---

deps.edn

brings in updated jruby which addresses some security issues

maint: bump asciidoctorj

---

bb.edn
deps.edn

bump deps that are not used in cljdoc prod

maint: bump safe clojure deps

---

deps.edn

these ones seem safe to do, leaving some others for later

maint: bump some clojure deps

---

deps.edn

clj-kondo - safe, not used in prod
sqlite-jdbc - nice to do alone and let it run a few days

maint: bump clj deps

---

deps.edn
package-lock.json
package.json

This catches us up to current - for now.

maint: bump clojure and npm deps

---

resources/public/cljdoc.css
src/cljdoc/render/api.clj
src/cljdoc/render/offline.clj

Platform specific docs and args styling adjusted

---

src/cljdoc/platforms.clj
src/cljdoc/render/api.clj

Was previously erroring out at render time.
Closes #701

Show protocol members differences across platform

---

bb.edn
deps.edn
package-lock.json
package.json
resources/asset-deps.edn

Of note:
- we are still holding off on pedestal until it comes out of beta, we might change our minds on that but for now...

maint: bump deps

---

src/cljdoc/render/api.clj

Now rendering instead of throwing.
Closes #721

Render invalid arglists as such

---

src/cljdoc/render/error.clj
src/cljdoc/server/pedestal.clj
src/cljdoc/util/repositories.clj

Was previously generating 500s for these.
Also refined 404 presentation a tad.
Addendum to #720

404 for CURRENT artifact URLs

---

src/cljdoc/server/pedestal.clj

Was previously throwing and returning 500.
Closes #726

Return 404 status when no badge found

---

src/cljdoc/render/api.clj

Non formattable arglists are now assumed to be invalid. Invalid arglists continue to be marked as such, but now just dumped as is.
Closes #728

Address: bad arglists are not always valid Clojure

---

src/cljdoc/render/api_searchset.clj

Searchsets now cope with regex in arglists

---

src/cljdoc/server/pedestal.clj
src/cljdoc/server/routes.clj

Don't use referer URL version for different lib

---

src/cljdoc/server/search/search.clj

Added a simple lock to avoid multiple concurrent writes to the Lucene index.
Also... noticed that when I added logging of index progress/performance, I neglected to remove old indexing code resulting needless double indexing of every artifact. So not doing that anymore.
Closes #695

Lock to avoid concurrent writes to lucene index

---

.circleci/config.yml

Got an auth error when on last deploy with nomad.
No clue as to why yet.

ci tweaks: report tools versions

---

doc/userguide/for-library-authors.adoc

docs: author guide: wikilink clarifications

---

src/cljdoc/render/api_searchset.clj

Support plaintext articles in single docset search

---

doc/userguide/for-library-authors.adoc

authors guide: clarify that clojars is required

---

bb.edn
doc/cljdoc-developer-technical-guide.adoc
doc/running-cljdoc-locally-dev.adoc
ops/README.adoc

bb version -> bb current-version
bb run     -> bb server
Closes #828

dev: rename bb tasks conflicting with bb internals

---

.circleci/config.yml

bb task rename: missed a usage

---

.circleci/config.yml

Makes CircleCI job steps easier to read on web.

ci: nit: name commands

---

test/cljdoc/util/repositories_test.clj

when you test against reality you need to adapt when reality changes

test: reality changed

---

deps.edn

mystery: prod is acting up

---

src/cljdoc/render/layout.clj

Recognize `bb`,`cljc` as code block lang ids

---

.parcelrc
bb.edn
package-lock.json
package.json
resources/asset-deps.edn
resources/public/cljdoc.html
resources/public/tachyons.css
src/cljdoc/render/layout.clj
src/cljdoc/render/offline.clj

Was 30em, now 45em
Closes #875

Implement a more reasonble screen width cutoff for mobile/desktop layout

---

modules/nvd-scan/nvd-suppressions.xml
modules/nvd-scan/ops/nvd-suppressions.xml

and turf nvd suppression file form old location

ops: suppress false positive CVEs [skip ci]

---

ops/exoscale/deploy/resources/cljdoc.jobspec.edn
script/docker_entrypoint.clj

After ssh port fowarding in, allow access to cljdoc server from jvisualvm

ops: allow jvisualvm

---

script/docker_entrypoint.clj

Can't currently connect from my dev box after ssh port forwarding. Long shot, but maybe.

Try localhost for rmi server for visualvm

---

ops/exoscale/deploy/resources/cljdoc.jobspec.edn

Kinda makes sense that if you want nomad to configure static ports, you configure them under... StaticPorts.
Maybe this will do the trick.

more visualvm config tweaks

---

ops/exoscale/deploy/resources/cljdoc.jobspec.edn

Try another thing that might not work!

ops: visualvm tweaks

---

ops/exoscale/deploy/src/cljdoc/deploy.clj

Nomad job creation API can return warnings.
Log them.

ops: deploy: log nomad warnings

---

src/cljdoc/server/search/api.clj
src/cljdoc/server/search/search.clj
test/cljdoc/server/search/api_test.clj

The Lucene IndexReader is threadsafe and the Lucene docs recommend that it be reused. I never bothered doing this because it does add some stateful complexity in that the IndexReader needs to be recreated if necessary (this will happen if the Lucene index has changed).
On prod we are seeing our RAM usage creep up slowly until it hovers around our docker container limit. This RAM usage is outside of the JVM heap.
The RAM usage might be Lucene's use of memory mapped files. I was curious to see if using Lucene's IndexReader in the recommended way would impact RAM usage.
The IndexWriter can also be long-lived, but our writes are so infrequent I do not currently see the benefit to keeping an IndexWriter around. And not closing an IndexWriter can lead to Lucene index corruption, a scenario I'd …

Reuse Lucene IndexReader

---

src/cljdoc/render/build_log.clj
src/cljdoc/util/datetime.clj
test/cljdoc/util/datetime_test.clj

Improve (human) readability of dates in build log

---

ops/exoscale/deploy/resources/cljdoc.jobspec.edn

This might help with or even maybe address #953

ops: tell traefik to only use gzip compression

---

src/cljdoc/server/release_monitor.clj

Use new clojars release feed API

---

js/single-docset-search.tsx

fix client-side docset search sub-tokenization

---

src/cljdoc/server/search/maven_central.clj
src/cljdoc/server/search/search.clj
src/cljdoc/util/sqlite_cache.clj

Log maven API calls

---

.circleci/config.yml

maint: bump ci to jdk23

---

.clj-kondo/config.edn
modules/cli/src/cljdoc/cli.clj
script/outdated.clj
src/cljdoc/analysis/service.clj
src/cljdoc/bundle.clj
src/cljdoc/render/layout.clj
src/cljdoc/render/offline.clj
src/cljdoc/server/api.clj
src/cljdoc/server/db_backup.clj
src/cljdoc/server/ingest.clj
src/cljdoc/server/pedestal.clj
src/cljdoc/server/routes.clj
src/cljdoc/storage/api.clj
src/cljdoc/util/scm.clj
src/cljdoc/util/sqlite_cache.clj

dev: lint unused destructured keys

---

src/cljdoc/util/sqlite_cache.clj
test/cljdoc/util/sqlite_cache_test.clj

Replace current redefs with injectable `:clock`.

dev: use java.time.Clock for sqlite cache

---

doc/CODE_OF_CONDUCT.adoc
ops/README.adoc
ops/exoscale/deploy/resources/cljdoc.jobspec.edn
ops/exoscale/deploy/src/cljdoc/deploy.clj
ops/exoscale/infrastructure/main.tf
src/cljdoc/util/fixref.clj
test/cljdoc/util/fixref_test.clj

Retire cljdoc.xyz domain

---

resources/config.edn

will turn it back on after I deal with #996

ops: turn off db backup for now

---

resources/asset-deps.edn
test/cljdoc/cli_integration_test.clj

Add support for groovy syntax highlighting

---

script/docker_entrypoint.clj

ops: compress heapdump with zstd

---

src/cljdoc/server/search/api.clj
src/cljdoc/server/search/clojars.clj
src/cljdoc/server/search/maven_central.clj
src/cljdoc/server/search/search.clj
test/cljdoc/server_integration_test.clj

adapt to maven search reliability

---

doc/userguide/for-library-authors.adoc

Unfortunately not simple enough to describe in the doc, so provide a couple of examples from the wild.
Closes #1059

lib author docs: deps.edn provided dep examples

---

front-end/src/cljdoc/client/namespace_scroll.cljs

mistake made detail view scrolling stick to top

fix bad var rename to fix nav scroll

---

deps.edn

Downgrade pedestal
